<a href="https://colab.research.google.com/github/Junaid-sadiq/Educhat/blob/main/nb/Gemma3_(1B).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

To run this, press "*Runtime*" and press "*Run all*" on a **free** Tesla T4 Google Colab instance!
<div class="align-center">
<a href="https://unsloth.ai/"><img src="https://github.com/unslothai/unsloth/raw/main/images/unsloth%20new%20logo.png" width="115"></a>
<a href="https://discord.gg/unsloth"><img src="https://github.com/unslothai/unsloth/raw/main/images/Discord button.png" width="145"></a>
<a href="https://docs.unsloth.ai/"><img src="https://github.com/unslothai/unsloth/blob/main/images/documentation%20green%20button.png?raw=true" width="125"></a></a> Join Discord if you need help + ⭐ <i>Star us on <a href="https://github.com/unslothai/unsloth">Github</a> </i> ⭐
</div>

To install Unsloth on your own computer, follow the installation instructions on our Github page [here](https://docs.unsloth.ai/get-started/installing-+-updating).

You will learn how to do [data prep](#Data), how to [train](#Train), how to [run the model](#Inference), & [how to save it](#Save)

### News

Unsloth now supports Text-to-Speech (TTS) models. Read our [guide here](https://docs.unsloth.ai/basics/text-to-speech-tts-fine-tuning).

Read our **[Qwen3 Guide](https://docs.unsloth.ai/basics/qwen3-how-to-run-and-fine-tune)** and check out our new **[Dynamic 2.0](https://docs.unsloth.ai/basics/unsloth-dynamic-2.0-ggufs)** quants which outperforms other quantization methods!

Visit our docs for all our [model uploads](https://docs.unsloth.ai/get-started/all-our-models) and [notebooks](https://docs.unsloth.ai/get-started/unsloth-notebooks).

### Installation

In [1]:
%%capture
import os
if "COLAB_" not in "".join(os.environ.keys()):
    !pip install unsloth
else:
    # Do this only in Colab notebooks! Otherwise use pip install unsloth
    !pip install --no-deps bitsandbytes accelerate xformers==0.0.29.post3 peft trl triton cut_cross_entropy unsloth_zoo
    !pip install sentencepiece protobuf "datasets>=3.4.1" huggingface_hub hf_transfer
    !pip install --no-deps unsloth

### Unsloth

`FastModel` supports loading nearly any model now! This includes Vision and Text models!

In [2]:
from unsloth import FastModel
import torch

fourbit_models = [
    # 4bit dynamic quants for superior accuracy and low memory use
    "unsloth/gemma-3-1b-it-unsloth-bnb-4bit",
    "unsloth/gemma-3-4b-it-unsloth-bnb-4bit",
    "unsloth/gemma-3-12b-it-unsloth-bnb-4bit",
    "unsloth/gemma-3-27b-it-unsloth-bnb-4bit",

    # Other popular models!
    "unsloth/Llama-3.1-8B",
    "unsloth/Llama-3.2-3B",
    "unsloth/Llama-3.3-70B",
    "unsloth/mistral-7b-instruct-v0.3",
    "unsloth/Phi-4",
] # More models at https://huggingface.co/unsloth

model, tokenizer = FastModel.from_pretrained(
    model_name = "unsloth/gemma-3-1b-it",
    max_seq_length = 2048, # Choose any for long context!
    load_in_4bit = True,  # 4 bit quantization to reduce memory
    load_in_8bit = False, # [NEW!] A bit more accurate, uses 2x memory
    full_finetuning = False, # [NEW!] We have full finetuning now!
    # token = "hf_...", # use one if using gated models
)

🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.
🦥 Unsloth Zoo will now patch everything to make training faster!
==((====))==  Unsloth 2025.6.2: Fast Gemma3 patching. Transformers: 4.52.4.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.741 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.6.0+cu124. CUDA: 7.5. CUDA Toolkit: 12.4. Triton: 3.2.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.29.post3. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!
Unsloth: Using float16 precision for gemma3 won't work! Using float32.

model.safetensors:   0%|          | 0.00/1.00G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/233 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/1.16M [00:00<?, ?B/s]

tokenizer.model:   0%|          | 0.00/4.69M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/33.4M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/35.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/670 [00:00<?, ?B/s]

We now add LoRA adapters so we only need to update a small amount of parameters!

In [3]:
model = FastModel.get_peft_model(
    model,
    finetune_vision_layers     = False, # Turn off for just text!
    finetune_language_layers   = True,  # Should leave on!
    finetune_attention_modules = True,  # Attention good for GRPO
    finetune_mlp_modules       = True,  # SHould leave on always!

    r = 8,           # Larger = higher accuracy, but might overfit
    lora_alpha = 8,  # Recommended alpha == r at least
    lora_dropout = 0,
    bias = "none",
    random_state = 3407,
)

Unsloth: Making `model.base_model.model.model` require gradients

<a name="Data"></a>
### Data Prep
We now use the `Gemma-3` format for conversation style finetunes. We use [Maxime Labonne's FineTome-100k](https://huggingface.co/datasets/mlabonne/FineTome-100k) dataset in ShareGPT style. Gemma-3 renders multi turn conversations like below:

```
<bos><start_of_turn>user
Hello!<end_of_turn>
<start_of_turn>model
Hey there!<end_of_turn>
```

We use our `get_chat_template` function to get the correct chat template. We support `zephyr, chatml, mistral, llama, alpaca, vicuna, vicuna_old, phi3, llama3, phi4, qwen2.5, gemma3` and more.

In [4]:
from unsloth.chat_templates import get_chat_template
tokenizer = get_chat_template(
    tokenizer,
    chat_template = "gemma-3",
)

In [5]:
from datasets import load_dataset
dataset = load_dataset("mlabonne/FineTome-100k", split = "train")

README.md:   0%|          | 0.00/982 [00:00<?, ?B/s]

data/train-00000-of-00001.parquet:   0%|          | 0.00/117M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/100000 [00:00<?, ? examples/s]

We now use `standardize_data_formats` to try converting datasets to the correct format for finetuning purposes!

In [6]:
from unsloth.chat_templates import standardize_data_formats
dataset = standardize_data_formats(dataset)

Unsloth: Standardizing formats (num_proc=2):   0%|          | 0/100000 [00:00<?, ? examples/s]

Let's see how row 100 looks like!

In [7]:
dataset[100]

{'conversations': [{'content': 'What is the modulus operator in programming and how can I use it to calculate the modulus of two given numbers?',
   'role': 'user'},
  {'content': 'In programming, the modulus operator is represented by the \'%\' symbol. It calculates the remainder when one number is divided by another. To calculate the modulus of two given numbers, you can use the modulus operator in the following way:\n\n```python\n# Calculate the modulus\nModulus = a % b\n\nprint("Modulus of the given numbers is: ", Modulus)\n```\n\nIn this code snippet, the variables \'a\' and \'b\' represent the two given numbers for which you want to calculate the modulus. By using the modulus operator \'%\', we calculate the remainder when \'a\' is divided by \'b\'. The result is then stored in the variable \'Modulus\'. Finally, the modulus value is printed using the \'print\' statement.\n\nFor example, if \'a\' is 10 and \'b\' is 4, the modulus calculation would be 10 % 4, which equals 2. Therefore, the output of the above code would be:\n\n```\nModulus of the given numbers is: 2\n```\n\nThis means that the modulus of 10 and 4 is 2.',
   'role': 'assistant'}],
 'source': 'infini-instruct-top-500k',
 'score': 4.774171352386475}

We now have to apply the chat template for `Gemma-3` onto the conversations, and save it to `text`. We remove the `<bos>` token using removeprefix(`'<bos>'`) since we're finetuning. The Processor will add this token before training and the model expects only one.

In [8]:
def formatting_prompts_func(examples):
   convos = examples["conversations"]
   texts = [tokenizer.apply_chat_template(convo, tokenize = False, add_generation_prompt = False).removeprefix('<bos>') for convo in convos]
   return { "text" : texts, }

dataset = dataset.map(formatting_prompts_func, batched = True)

Map:   0%|          | 0/100000 [00:00<?, ? examples/s]

Let's see how the chat template did! Notice there is no `<bos>` token as the processor tokenizer will be adding one.

In [9]:
dataset[100]["text"]

'<start_of_turn>user\nWhat is the modulus operator in programming and how can I use it to calculate the modulus of two given numbers?<end_of_turn>\n<start_of_turn>model\nIn programming, the modulus operator is represented by the \'%\' symbol. It calculates the remainder when one number is divided by another. To calculate the modulus of two given numbers, you can use the modulus operator in the following way:\n\n```python\n# Calculate the modulus\nModulus = a % b\n\nprint("Modulus of the given numbers is: ", Modulus)\n```\n\nIn this code snippet, the variables \'a\' and \'b\' represent the two given numbers for which you want to calculate the modulus. By using the modulus operator \'%\', we calculate the remainder when \'a\' is divided by \'b\'. The result is then stored in the variable \'Modulus\'. Finally, the modulus value is printed using the \'print\' statement.\n\nFor example, if \'a\' is 10 and \'b\' is 4, the modulus calculation would be 10 % 4, which equals 2. Therefore, the output of the above code would be:\n\n```\nModulus of the given numbers is: 2\n```\n\nThis means that the modulus of 10 and 4 is 2.<end_of_turn>\n'

<a name="Train"></a>
### Train the model
Now let's use Huggingface TRL's `SFTTrainer`! More docs here: [TRL SFT docs](https://huggingface.co/docs/trl/sft_trainer). We do 60 steps to speed things up, but you can set `num_train_epochs=1` for a full run, and turn off `max_steps=None`.

In [10]:
from trl import SFTTrainer, SFTConfig
trainer = SFTTrainer(
    model = model,
    tokenizer = tokenizer,
    train_dataset = dataset,
    eval_dataset = None, # Can set up evaluation!
    args = SFTConfig(
        dataset_text_field = "text",
        per_device_train_batch_size = 2,
        gradient_accumulation_steps = 4, # Use GA to mimic batch size!
        warmup_steps = 5,
        # num_train_epochs = 1, # Set this for 1 full training run.
        max_steps = 30,
        learning_rate = 2e-4, # Reduce to 2e-5 for long training runs
        logging_steps = 1,
        optim = "adamw_8bit",
        weight_decay = 0.01,
        lr_scheduler_type = "linear",
        seed = 3407,
        report_to = "none", # Use this for WandB etc
        dataset_num_proc=2,
    ),
)

Unsloth: Switching to float32 training since model cannot work with float16

Unsloth: Tokenizing ["text"] (num_proc=2):   0%|          | 0/100000 [00:00<?, ? examples/s]

We also use Unsloth's `train_on_completions` method to only train on the assistant outputs and ignore the loss on the user's inputs. This helps increase accuracy of finetunes!

In [11]:
from unsloth.chat_templates import train_on_responses_only
trainer = train_on_responses_only(
    trainer,
    instruction_part = "<start_of_turn>user\n",
    response_part = "<start_of_turn>model\n",
)

Map (num_proc=2):   0%|          | 0/100000 [00:00<?, ? examples/s]

Let's verify masking the instruction part is done! Let's print the 100th row again.  Notice how the sample only has a single `<bos>` as expected!

In [12]:
tokenizer.decode(trainer.train_dataset[100]["input_ids"])

'<bos><start_of_turn>user\nWhat is the modulus operator in programming and how can I use it to calculate the modulus of two given numbers?<end_of_turn>\n<start_of_turn>model\nIn programming, the modulus operator is represented by the \'%\' symbol. It calculates the remainder when one number is divided by another. To calculate the modulus of two given numbers, you can use the modulus operator in the following way:\n\n```python\n# Calculate the modulus\nModulus = a % b\n\nprint("Modulus of the given numbers is: ", Modulus)\n```\n\nIn this code snippet, the variables \'a\' and \'b\' represent the two given numbers for which you want to calculate the modulus. By using the modulus operator \'%\', we calculate the remainder when \'a\' is divided by \'b\'. The result is then stored in the variable \'Modulus\'. Finally, the modulus value is printed using the \'print\' statement.\n\nFor example, if \'a\' is 10 and \'b\' is 4, the modulus calculation would be 10 % 4, which equals 2. Therefore, the output of the above code would be:\n\n```\nModulus of the given numbers is: 2\n```\n\nThis means that the modulus of 10 and 4 is 2.<end_of_turn>\n'

Now let's print the masked out example - you should see only the answer is present:

In [13]:
tokenizer.decode([tokenizer.pad_token_id if x == -100 else x for x in trainer.train_dataset[100]["labels"]]).replace(tokenizer.pad_token, " ")

'                               In programming, the modulus operator is represented by the \'%\' symbol. It calculates the remainder when one number is divided by another. To calculate the modulus of two given numbers, you can use the modulus operator in the following way:\n\n```python\n# Calculate the modulus\nModulus = a % b\n\nprint("Modulus of the given numbers is: ", Modulus)\n```\n\nIn this code snippet, the variables \'a\' and \'b\' represent the two given numbers for which you want to calculate the modulus. By using the modulus operator \'%\', we calculate the remainder when \'a\' is divided by \'b\'. The result is then stored in the variable \'Modulus\'. Finally, the modulus value is printed using the \'print\' statement.\n\nFor example, if \'a\' is 10 and \'b\' is 4, the modulus calculation would be 10 % 4, which equals 2. Therefore, the output of the above code would be:\n\n```\nModulus of the given numbers is: 2\n```\n\nThis means that the modulus of 10 and 4 is 2.<end_of_turn>\n'

In [14]:
# @title Show current memory stats
gpu_stats = torch.cuda.get_device_properties(0)
start_gpu_memory = round(torch.cuda.max_memory_reserved() / 1024 / 1024 / 1024, 3)
max_memory = round(gpu_stats.total_memory / 1024 / 1024 / 1024, 3)
print(f"GPU = {gpu_stats.name}. Max memory = {max_memory} GB.")
print(f"{start_gpu_memory} GB of memory reserved.")

GPU = Tesla T4. Max memory = 14.741 GB.
1.512 GB of memory reserved.

Let's train the model! To resume a training run, set `trainer.train(resume_from_checkpoint = True)`

In [15]:
trainer_stats = trainer.train()

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 100,000 | Num Epochs = 1 | Total steps = 30
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
 "-____-"     Trainable parameters = 6,522,880/1,000,000,000 (0.65% trained)
`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`.

Unsloth: Will smartly offload gradients to save VRAM!

In [16]:
# @title Show final memory and time stats
used_memory = round(torch.cuda.max_memory_reserved() / 1024 / 1024 / 1024, 3)
used_memory_for_lora = round(used_memory - start_gpu_memory, 3)
used_percentage = round(used_memory / max_memory * 100, 3)
lora_percentage = round(used_memory_for_lora / max_memory * 100, 3)
print(f"{trainer_stats.metrics['train_runtime']} seconds used for training.")
print(
    f"{round(trainer_stats.metrics['train_runtime']/60, 2)} minutes used for training."
)
print(f"Peak reserved memory = {used_memory} GB.")
print(f"Peak reserved memory for training = {used_memory_for_lora} GB.")
print(f"Peak reserved memory % of max memory = {used_percentage} %.")
print(f"Peak reserved memory for training % of max memory = {lora_percentage} %.")

193.1888 seconds used for training.
3.22 minutes used for training.
Peak reserved memory = 1.977 GB.
Peak reserved memory for training = 0.465 GB.
Peak reserved memory % of max memory = 13.412 %.
Peak reserved memory for training % of max memory = 3.154 %.

<a name="Inference"></a>
### Inference
Let's run the model via Unsloth native inference! According to the `Gemma-3` team, the recommended settings for inference are `temperature = 1.0, top_p = 0.95, top_k = 64`

In [19]:
from unsloth.chat_templates import get_chat_template
tokenizer = get_chat_template(
    tokenizer,
    chat_template = "gemma-3",
)
messages = [{
    "role": "user",
    "content": [{
        "type" : "text",
        "text" : "Continue the sequence: 1, 1, 2, 3, 5, 8,",
    }]
}]
text = tokenizer.apply_chat_template(
    messages,
    add_generation_prompt = True, # Must add for generation
    tokenization: False
)
outputs = model.generate(
    **tokenizer([text], return_tensors = "pt").to("cuda"),
    max_new_tokens = 64, # Increase for longer outputs!
    # Recommended Gemma-3 settings!
    temperature = 1.0, top_p = 0.95, top_k = 64,
)
tokenizer.batch_decode(outputs)

SyntaxError: positional argument follows keyword argument (<ipython-input-19-1442712065>, line 16)

 You can also use a `TextStreamer` for continuous inference - so you can see the generation token by token, instead of waiting the whole time!

In [ ]:
messages = [{
    "role": "user",
    "content": [{"type" : "text", "text" : "Why is the sky blue?",}]
}]
text = tokenizer.apply_chat_template(
    messages,
    add_generation_prompt = True, # Must add for generation
)

from transformers import TextStreamer
_ = model.generate(
    **tokenizer([text], return_tensors = "pt").to("cuda"),
    max_new_tokens = 64, # Increase for longer outputs!
    # Recommended Gemma-3 settings!
    temperature = 1.0, top_p = 0.95, top_k = 64,
    streamer = TextStreamer(tokenizer, skip_prompt = True),
)

Okay, let's break down why the sky is blue! It's a fascinating phenomenon that boils down to a combination of physics and light. Here's the explanation:

**1. Sunlight and its Colors:**

* Sunlight, which appears white to us, is actually made up of *all* the

<a name="Save"></a>
### Saving, loading finetuned models
To save the final model as LoRA adapters, either use Huggingface's `push_to_hub` for an online save or `save_pretrained` for a local save.

**[NOTE]** This ONLY saves the LoRA adapters, and not the full model. To save to 16bit or GGUF, scroll down!

In [20]:
model.save_pretrained("gemma-3")  # Local saving
tokenizer.save_pretrained("gemma-3")
# model.push_to_hub("HF_ACCOUNT/gemma-3", token = "...") # Online saving
# tokenizer.push_to_hub("HF_ACCOUNT/gemma-3", token = "...") # Online saving

('gemma-3/tokenizer_config.json',
 'gemma-3/special_tokens_map.json',
 'gemma-3/chat_template.jinja',
 'gemma-3/tokenizer.model',
 'gemma-3/added_tokens.json',
 'gemma-3/tokenizer.json')

In [22]:
import pandas as pd
from datasets import Dataset, concatenate_datasets
import kagglehub
import os
import json
# === 2. Load Your Custom Dataset ===
print("📖 Loading your custom dataset...")
df = pd.read_csv("/content/final_dataset_combined.csv")
print(f"✓ Custom dataset: {len(df)} rows with columns: {df.columns.tolist()}")

def convert_custom_to_conversations(df):
    """Convert your custom dataset to conversations format"""
    formatted_data = []

    for idx, row in df.iterrows():
        # Create user message by combining instruction and input
        user_content = row['instruction']
        if pd.notna(row['input']) and str(row['input']).strip():
            user_content += f"\n\n{row['input']}"

        # Create conversation in the format Gemma-3 expects
        conversation = [
            {"role": "user", "content": user_content},
            {"role": "assistant", "content": row['output']}
        ]

        formatted_data.append({"conversations": conversation})

    return formatted_data

custom_data = convert_custom_to_conversations(df)
custom_dataset = Dataset.from_list(custom_data)
print(f"✓ Custom dataset: {len(custom_dataset)} examples")

📖 Loading your custom dataset...
✓ Custom dataset: 812 rows with columns: ['instruction', 'input', 'output']
✓ Custom dataset: 812 examples

In [23]:
from unsloth.chat_templates import standardize_data_formats
dataset = standardize_data_formats(custom_dataset)

Unsloth: Standardizing formats (num_proc=2):   0%|          | 0/812 [00:00<?, ? examples/s]

In [24]:
custom_dataset[100]

{'conversations': [{'content': "You are Kiran, an AI assistant from Tampere University. Answer the following question from a student based on the provided context:\n\nHow does the Fourier-analytic approach used in the proof of Bogolyubov's lemma leverage the size of Fourier coefficients to construct a large subspace within $ 2A - 2A $, and what role does the threshold $ \\alpha^{3/2} $ play in this construction?",
   'role': 'user'},
  {'content': "The Fourier-analytic approach in the proof of Bogolyubov's lemma uses the size of Fourier coefficients to extract a large subspace within $ 2A - 2A $ by distinguishing between large and small Fourier coefficients. The set $ A $, being a subset of $ \\mathbb{F}_2^n $ with density $ \\alpha $, has a convolution $ f = 1_A * 1_A * 1_A * 1_A $ (or $ 2A - 2A $) whose support is the sumset $ 2A - 2A $. The Fourier transform of $ f $ is given by $ \\widehat{f}(\\xi) = |\\widehat{1_A}(\\xi)|^4 $, and its inverse Fourier transform allows the evaluation of $ f(x) $ in terms of the Fourier coefficients of $ 1_A $.\n\nTo construct a large subspace within $ 2A - 2A $, the proof defines a set $ R $ consisting of all Fourier characters $ \\xi $ for which $ |\\widehat{1_A}(\\xi)| \\geq \\alpha^{3/2} $. This threshold $ \\alpha^{3/2} $ is critical because it ensures that the number of such characters is small. By Parseval's identity, the sum of the squares of the Fourier coefficients equals the $ L^2 $-norm of $ 1_A $, which is $ \\alpha $. Thus, the number of characters in $ R $ is at most $ 1/\\alpha^2 $, as the sum of the squares of the large coefficients cannot exceed $ \\alpha $.\n\nThe orthogonal complement $ R^\\perp $ is a subspace of $ \\mathbb{F}_2^n $, and it is shown that $ f $ is positive on $ R^\\perp $. This is achieved by evaluating $ f(x) $ for $ x \\in R^\\perp $ using the Fourier inversion formula. The main term in the sum is $ \\alpha^4 $, and the contributions from the remaining Fourier coefficients are small, ensuring that $ f(x) $ remains positive. As a result, $ R^\\perp $ is contained in the support of $ f $, which is $ 2A - 2A $.\n\nThe threshold $ \\alpha^{3/2} $ thus plays a central role in defining the set $ R $, ensuring it is small and that its orthogonal complement $ R^\\perp $ is large (with codimension at most $ 1/\\alpha^2 $) and lies within $ 2A - 2A $. This construction guarantees the existence of a large subspace within the iterated sumset, leveraging the interplay between Fourier analysis and the size of the Fourier coefficients.",
   'role': 'assistant'}]}

In [28]:
def formatting_prompts_func(examples):
   convos = examples["conversations"]
   texts = [tokenizer.apply_chat_template(convo, tokenize = False, add_generation_prompt = False).removeprefix('<bos>') for convo in convos]
   return { "text" : texts, }

custom_dataset = custom_dataset.map(formatting_prompts_func, batched = True)

Map:   0%|          | 0/812 [00:00<?, ? examples/s]

In [29]:
custom_dataset[100]["text"]

"<start_of_turn>user\nYou are Kiran, an AI assistant from Tampere University. Answer the following question from a student based on the provided context:\n\nHow does the Fourier-analytic approach used in the proof of Bogolyubov's lemma leverage the size of Fourier coefficients to construct a large subspace within $ 2A - 2A $, and what role does the threshold $ \\alpha^{3/2} $ play in this construction?<end_of_turn>\n<start_of_turn>model\nThe Fourier-analytic approach in the proof of Bogolyubov's lemma uses the size of Fourier coefficients to extract a large subspace within $ 2A - 2A $ by distinguishing between large and small Fourier coefficients. The set $ A $, being a subset of $ \\mathbb{F}_2^n $ with density $ \\alpha $, has a convolution $ f = 1_A * 1_A * 1_A * 1_A $ (or $ 2A - 2A $) whose support is the sumset $ 2A - 2A $. The Fourier transform of $ f $ is given by $ \\widehat{f}(\\xi) = |\\widehat{1_A}(\\xi)|^4 $, and its inverse Fourier transform allows the evaluation of $ f(x) $ in terms of the Fourier coefficients of $ 1_A $.\n\nTo construct a large subspace within $ 2A - 2A $, the proof defines a set $ R $ consisting of all Fourier characters $ \\xi $ for which $ |\\widehat{1_A}(\\xi)| \\geq \\alpha^{3/2} $. This threshold $ \\alpha^{3/2} $ is critical because it ensures that the number of such characters is small. By Parseval's identity, the sum of the squares of the Fourier coefficients equals the $ L^2 $-norm of $ 1_A $, which is $ \\alpha $. Thus, the number of characters in $ R $ is at most $ 1/\\alpha^2 $, as the sum of the squares of the large coefficients cannot exceed $ \\alpha $.\n\nThe orthogonal complement $ R^\\perp $ is a subspace of $ \\mathbb{F}_2^n $, and it is shown that $ f $ is positive on $ R^\\perp $. This is achieved by evaluating $ f(x) $ for $ x \\in R^\\perp $ using the Fourier inversion formula. The main term in the sum is $ \\alpha^4 $, and the contributions from the remaining Fourier coefficients are small, ensuring that $ f(x) $ remains positive. As a result, $ R^\\perp $ is contained in the support of $ f $, which is $ 2A - 2A $.\n\nThe threshold $ \\alpha^{3/2} $ thus plays a central role in defining the set $ R $, ensuring it is small and that its orthogonal complement $ R^\\perp $ is large (with codimension at most $ 1/\\alpha^2 $) and lies within $ 2A - 2A $. This construction guarantees the existence of a large subspace within the iterated sumset, leveraging the interplay between Fourier analysis and the size of the Fourier coefficients.<end_of_turn>\n"

In [31]:
from trl import SFTTrainer, SFTConfig
trainer = SFTTrainer(
    model = model,
    tokenizer = tokenizer,
    train_dataset = custom_dataset,
    eval_dataset = None, # Can set up evaluation!
    args = SFTConfig(
        dataset_text_field = "text",
        per_device_train_batch_size = 2,
        gradient_accumulation_steps = 4, # Use GA to mimic batch size!
        warmup_steps = 5,
        # num_train_epochs = 1, # Set this for 1 full training run.
        max_steps = 30,
        learning_rate = 2e-4, # Reduce to 2e-5 for long training runs
        logging_steps = 1,
        optim = "adamw_8bit",
        weight_decay = 0.01,
        lr_scheduler_type = "linear",
        seed = 3407,
        report_to = "none", # Use this for WandB etc
        dataset_num_proc=2,
    ),
)

Unsloth: Switching to float32 training since model cannot work with float16

Unsloth: Tokenizing ["text"] (num_proc=2):   0%|          | 0/812 [00:00<?, ? examples/s]

In [32]:
from unsloth.chat_templates import train_on_responses_only
trainer = train_on_responses_only(
    trainer,
    instruction_part = "<start_of_turn>user\n",
    response_part = "<start_of_turn>model\n",
)

Map (num_proc=2):   0%|          | 0/812 [00:00<?, ? examples/s]

In [33]:
tokenizer.decode(trainer.train_dataset[100]["input_ids"])

"<bos><start_of_turn>user\nYou are Kiran, an AI assistant from Tampere University. Answer the following question from a student based on the provided context:\n\nHow does the Fourier-analytic approach used in the proof of Bogolyubov's lemma leverage the size of Fourier coefficients to construct a large subspace within $ 2A - 2A $, and what role does the threshold $ \\alpha^{3/2} $ play in this construction?<end_of_turn>\n<start_of_turn>model\nThe Fourier-analytic approach in the proof of Bogolyubov's lemma uses the size of Fourier coefficients to extract a large subspace within $ 2A - 2A $ by distinguishing between large and small Fourier coefficients. The set $ A $, being a subset of $ \\mathbb{F}_2^n $ with density $ \\alpha $, has a convolution $ f = 1_A * 1_A * 1_A * 1_A $ (or $ 2A - 2A $) whose support is the sumset $ 2A - 2A $. The Fourier transform of $ f $ is given by $ \\widehat{f}(\\xi) = |\\widehat{1_A}(\\xi)|^4 $, and its inverse Fourier transform allows the evaluation of $ f(x) $ in terms of the Fourier coefficients of $ 1_A $.\n\nTo construct a large subspace within $ 2A - 2A $, the proof defines a set $ R $ consisting of all Fourier characters $ \\xi $ for which $ |\\widehat{1_A}(\\xi)| \\geq \\alpha^{3/2} $. This threshold $ \\alpha^{3/2} $ is critical because it ensures that the number of such characters is small. By Parseval's identity, the sum of the squares of the Fourier coefficients equals the $ L^2 $-norm of $ 1_A $, which is $ \\alpha $. Thus, the number of characters in $ R $ is at most $ 1/\\alpha^2 $, as the sum of the squares of the large coefficients cannot exceed $ \\alpha $.\n\nThe orthogonal complement $ R^\\perp $ is a subspace of $ \\mathbb{F}_2^n $, and it is shown that $ f $ is positive on $ R^\\perp $. This is achieved by evaluating $ f(x) $ for $ x \\in R^\\perp $ using the Fourier inversion formula. The main term in the sum is $ \\alpha^4 $, and the contributions from the remaining Fourier coefficients are small, ensuring that $ f(x) $ remains positive. As a result, $ R^\\perp $ is contained in the support of $ f $, which is $ 2A - 2A $.\n\nThe threshold $ \\alpha^{3/2} $ thus plays a central role in defining the set $ R $, ensuring it is small and that its orthogonal complement $ R^\\perp $ is large (with codimension at most $ 1/\\alpha^2 $) and lies within $ 2A - 2A $. This construction guarantees the existence of a large subspace within the iterated sumset, leveraging the interplay between Fourier analysis and the size of the Fourier coefficients.<end_of_turn>\n"

In [34]:
tokenizer.decode([tokenizer.pad_token_id if x == -100 else x for x in trainer.train_dataset[100]["labels"]]).replace(tokenizer.pad_token, " ")

"                                                                                              The Fourier-analytic approach in the proof of Bogolyubov's lemma uses the size of Fourier coefficients to extract a large subspace within $ 2A - 2A $ by distinguishing between large and small Fourier coefficients. The set $ A $, being a subset of $ \\mathbb{F}_2^n $ with density $ \\alpha $, has a convolution $ f = 1_A * 1_A * 1_A * 1_A $ (or $ 2A - 2A $) whose support is the sumset $ 2A - 2A $. The Fourier transform of $ f $ is given by $ \\widehat{f}(\\xi) = |\\widehat{1_A}(\\xi)|^4 $, and its inverse Fourier transform allows the evaluation of $ f(x) $ in terms of the Fourier coefficients of $ 1_A $.\n\nTo construct a large subspace within $ 2A - 2A $, the proof defines a set $ R $ consisting of all Fourier characters $ \\xi $ for which $ |\\widehat{1_A}(\\xi)| \\geq \\alpha^{3/2} $. This threshold $ \\alpha^{3/2} $ is critical because it ensures that the number of such characters is small. By Parseval's identity, the sum of the squares of the Fourier coefficients equals the $ L^2 $-norm of $ 1_A $, which is $ \\alpha $. Thus, the number of characters in $ R $ is at most $ 1/\\alpha^2 $, as the sum of the squares of the large coefficients cannot exceed $ \\alpha $.\n\nThe orthogonal complement $ R^\\perp $ is a subspace of $ \\mathbb{F}_2^n $, and it is shown that $ f $ is positive on $ R^\\perp $. This is achieved by evaluating $ f(x) $ for $ x \\in R^\\perp $ using the Fourier inversion formula. The main term in the sum is $ \\alpha^4 $, and the contributions from the remaining Fourier coefficients are small, ensuring that $ f(x) $ remains positive. As a result, $ R^\\perp $ is contained in the support of $ f $, which is $ 2A - 2A $.\n\nThe threshold $ \\alpha^{3/2} $ thus plays a central role in defining the set $ R $, ensuring it is small and that its orthogonal complement $ R^\\perp $ is large (with codimension at most $ 1/\\alpha^2 $) and lies within $ 2A - 2A $. This construction guarantees the existence of a large subspace within the iterated sumset, leveraging the interplay between Fourier analysis and the size of the Fourier coefficients.<end_of_turn>\n"

In [35]:
trainer_stats = trainer.train()

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 812 | Num Epochs = 1 | Total steps = 30
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
 "-____-"     Trainable parameters = 6,522,880/1,000,000,000 (0.65% trained)

In [37]:
from unsloth.chat_templates import get_chat_template
tokenizer = get_chat_template(
    tokenizer,
    chat_template = "gemma-3",
)
messages = [{
    "role": "user",
    "content": [{
        "type" : "text",
        "text" : "Continue the sequence: 1, 1, 2, 3, 5, 8,",
    }]
}]
# Generate the text string using the chat template
text = tokenizer.apply_chat_template(
    messages,
    add_generation_prompt = True, # Must add for generation
    tokenize = False # Ensure we get a string, not token IDs
)
outputs = model.generate(
    # Tokenize the text string before passing to model.generate
    **tokenizer([text], return_tensors = "pt").to("cuda"),
    max_new_tokens = 64, # Increase for longer outputs!
    # Recommended Gemma-3 settings!
    temperature = 1.0, top_p = 0.95, top_k = 64,
)
tokenizer.batch_decode(outputs)

You have set `compile_config`, but we are unable to meet the criteria for compilation. Compilation will be skipped.

['<bos><bos><start_of_turn>user\nContinue the sequence: 1, 1, 2, 3, 5, 8,<end_of_turn>\n<start_of_turn>model\nThe sequence is the sequence of primes, which are numbers from 1 to 100 inclusive that are not divisible by any other integer except 1 and themselves. For example, 2, 3, 5, 7, 11, 13, 17, 19']

Now if you want to load the LoRA adapters we just saved for inference, set `False` to `True`:

In [39]:
if False:
    from unsloth import FastModel
    model, tokenizer = FastModel.from_pretrained(
        model_name = "lora_model", # YOUR MODEL YOU USED FOR TRAINING
        max_seq_length = 2048,
        load_in_4bit = True,
    )

messages = [{
    "role": "user",
    "content": [{"type" : "text", "text" : "What is Gemma-3?",}]
}]
text = tokenizer.apply_chat_template(
    messages,
    add_generation_prompt = True, # Must add for generation
    tokenize = False
)

from transformers import TextStreamer
_ = model.generate(
    **tokenizer([text], return_tensors = "pt").to("cuda"),
    max_new_tokens = 64, # Increase for longer outputs!
    # Recommended Gemma-3 settings!
    temperature = 1.0, top_p = 0.95, top_k = 64,
    streamer = TextStreamer(tokenizer, skip_prompt = True),
)

Gemma is an open-source language model from Google that builds upon the original Gemma language model to achieve strong performance on language tasks. The original Gemma model was trained on a large dataset of text and images, which allowed the researchers to develop a more general model architecture. The development of Gemma is inspired by other open-

### Saving to float16 for VLLM

We also support saving to `float16` directly for deployment! We save it in the folder `gemma-3-finetune`. Set `if False` to `if True` to let it run!

In [41]:
if True: # Change to True to save finetune!
    model.save_pretrained_merged("gemma-3-finetune", tokenizer)

Found HuggingFace hub cache directory: /root/.cache/huggingface/hub
Checking cache directory for required files...
Cache check failed: model.safetensors not found in local cache.
Not all required files found in cache. Will proceed with downloading.

Unsloth: Merging weights into 16bit:   0%|          | 0/1 [00:00<?, ?it/s]

model.safetensors:   0%|          | 0.00/2.00G [00:00<?, ?B/s]

Unsloth: Merging weights into 16bit: 100%|██████████| 1/1 [05:45<00:00, 345.39s/it]

In [49]:
# Load custom dataset
import pandas as pd
from datasets import Dataset, concatenate_datasets
import kagglehub
import os
import json

from google.colab import userdata
os.environ['KAGGLE_USERNAME'] = 'junaidsadiq1'
os.environ['KAGGLE_KEY'] = 'KAGGLE_KEY'

print("🔄 Loading and combining both datasets...")

# === 1. Load ArXiv Dataset ===
print("📚 Loading ArXiv dataset...")
path = kagglehub.dataset_download("Cornell-University/arxiv")
file_path = os.path.join(path, 'arxiv-metadata-oai-snapshot.json')

def create_arxiv_conversations(file_path, percentage=0.1):
    """Create conversations from ArXiv papers"""
    with open(file_path, 'r') as f:
        total_lines = sum(1 for line in f)

    lines_to_load = int(total_lines * percentage)
    print(f"Loading {lines_to_load} ArXiv papers ({percentage*100}% of dataset)")

    conversations = []
    with open(file_path, 'r') as f:
        for i, line in enumerate(f):
            if i >= lines_to_load:
                break
            try:
                paper = json.loads(line)
                user_prompt = f"Summarize the paper titled '{paper.get('title', 'No title available')}'."
                assistant_response = paper.get('abstract', 'Abstract not available.')

                if user_prompt and assistant_response:
                    conversation = [
                        {"role": "user", "content": user_prompt},
                        {"role": "assistant", "content": assistant_response}
                    ]
                    conversations.append({"conversations": conversation})
            except json.JSONDecodeError:
                continue
    return conversations

arxiv_data = create_arxiv_conversations(file_path, percentage=0.10)  # only 10% for gemma 1b
arxiv_dataset = Dataset.from_list(arxiv_data)
print(f"✓ ArXiv dataset: {len(arxiv_dataset)} examples")

# Apply the formatting function and update the arxiv_dataset variable
def formatting_prompts_func(examples):
   convos = examples["conversations"]
   texts = [tokenizer.apply_chat_template(convo, tokenize = False, add_generation_prompt = False).removeprefix('<bos>') for convo in convos]
   return { "text" : texts, }

# Corrected line: apply map to arxiv_dataset and reassign
arxiv_dataset = arxiv_dataset.map(formatting_prompts_func, batched = True)

🔄 Loading and combining both datasets...
📚 Loading ArXiv dataset...
Loading 275492 ArXiv papers (10.0% of dataset)
✓ ArXiv dataset: 275492 examples

Map:   0%|          | 0/275492 [00:00<?, ? examples/s]

In [50]:
arxiv_dataset[100]['text']

"<start_of_turn>user\nSummarize the paper titled 'The birth of string theory'.<end_of_turn>\n<start_of_turn>model\nIn this contribution we go through the developments that in the years 1968 to\n1974 led from the Veneziano model to the bosonic string.<end_of_turn>\n"

In [ ]:
from trl import SFTTrainer, SFTConfig
trainer = SFTTrainer(
    model = model,
    tokenizer = tokenizer,
    train_dataset = custom_dataset,
    eval_dataset = None, # Can set up evaluation!
    args = SFTConfig(
        dataset_text_field = "text",
        per_device_train_batch_size = 2,
        gradient_accumulation_steps = 4, # Use GA to mimic batch size!
        warmup_steps = 5,
        # num_train_epochs = 1, # Set this for 1 full training run.
        max_steps = 30,
        learning_rate = 2e-4, # Reduce to 2e-5 for long training runs
        logging_steps = 1,
        optim = "adamw_8bit",
        weight_decay = 0.01,
        lr_scheduler_type = "linear",
        seed = 3407,
        report_to = "none", # Use this for WandB etc
        dataset_num_proc=2,
    ),
)

Unsloth: Switching to float32 training since model cannot work with float16

Unsloth: Tokenizing ["text"] (num_proc=2):   0%|          | 0/275492 [00:00<?, ? examples/s]

If you want to upload / push to your Hugging Face account, set `if False` to `if True` and add your Hugging Face token and upload location!

In [ ]:
if False: # Change to True to upload finetune
    model.push_to_hub_merged(
        "HF_ACCOUNT/gemma-3-finetune", tokenizer,
        token = "hf_..."
    )

### GGUF / llama.cpp Conversion
To save to `GGUF` / `llama.cpp`, we support it natively now for all models! For now, you can convert easily to `Q8_0, F16 or BF16` precision. `Q4_K_M` for 4bit will come later!

In [ ]:
if False: # Change to True to save to GGUF
    model.save_pretrained_gguf(
        "gemma-3-finetune",
        quantization_type = "Q8_0", # For now only Q8_0, BF16, F16 supported
    )

Likewise, if you want to instead push to GGUF to your Hugging Face account, set `if False` to `if True` and add your Hugging Face token and upload location!

In [ ]:
if False: # Change to True to upload GGUF
    model.push_to_hub_gguf(
        "gemma-3-finetune",
        quantization_type = "Q8_0", # Only Q8_0, BF16, F16 supported
        repo_id = "HF_ACCOUNT/gemma-finetune-gguf",
        token = "hf_...",
    )

Now, use the `gemma-3-finetune.gguf` file or `gemma-3-finetune-Q4_K_M.gguf` file in llama.cpp or a UI based system like Jan or Open WebUI. You can install Jan [here](https://github.com/janhq/jan) and Open WebUI [here](https://github.com/open-webui/open-webui)

And we're done! If you have any questions on Unsloth, we have a [Discord](https://discord.gg/unsloth) channel! If you find any bugs or want to keep updated with the latest LLM stuff, or need help, join projects etc, feel free to join our Discord!

Some other links:
1. Train your own reasoning model - Llama GRPO notebook [Free Colab](https://colab.research.google.com/github/unslothai/notebooks/blob/main/nb/Llama3.1_(8B)-GRPO.ipynb)
2. Saving finetunes to Ollama. [Free notebook](https://colab.research.google.com/github/unslothai/notebooks/blob/main/nb/Llama3_(8B)-Ollama.ipynb)
3. Llama 3.2 Vision finetuning - Radiography use case. [Free Colab](https://colab.research.google.com/github/unslothai/notebooks/blob/main/nb/Llama3.2_(11B)-Vision.ipynb)
6. See notebooks for DPO, ORPO, Continued pretraining, conversational finetuning and more on our [documentation](https://docs.unsloth.ai/get-started/unsloth-notebooks)!

<div class="align-center">
  <a href="https://unsloth.ai"><img src="https://github.com/unslothai/unsloth/raw/main/images/unsloth%20new%20logo.png" width="115"></a>
  <a href="https://discord.gg/unsloth"><img src="https://github.com/unslothai/unsloth/raw/main/images/Discord.png" width="145"></a>
  <a href="https://docs.unsloth.ai/"><img src="https://github.com/unslothai/unsloth/blob/main/images/documentation%20green%20button.png?raw=true" width="125"></a>

  Join Discord if you need help + ⭐️ <i>Star us on <a href="https://github.com/unslothai/unsloth">Github</a> </i> ⭐️
</div>