**Read our [Gemma 3 blog](https://unsloth.ai/blog/gemma3) for what's new in Unsloth and our [Reasoning blog](https://unsloth.ai/blog/r1-reasoning) on how to train reasoning models.**

Visit our docs for all our [model uploads](https://docs.unsloth.ai/get-started/all-our-models) and [notebooks](https://docs.unsloth.ai/get-started/unsloth-notebooks).

### Installation

In [ ]:
import os
if "COLAB_" not in "".join(os.environ.keys()):
    !pip install unsloth
else:
    # Do this only in Colab notebooks! Otherwise use pip install unsloth
    !pip install --no-deps bitsandbytes accelerate xformers==0.0.29.post3 peft trl triton cut_cross_entropy unsloth_zoo
    !pip install sentencepiece protobuf datasets huggingface_hub hf_transfer
    !pip install --no-deps unsloth
# Install latest Hugging Face for Gemma-3!
!pip install --no-deps git+https://github.com/huggingface/transformers@v4.49.0-Gemma-3

In [1]:
from unsloth import FastModel
import torch

fourbit_models = [
    # 4bit dynamic quants for superior accuracy and low memory use
    "unsloth/gemma-3-1b-it-unsloth-bnb-4bit",
    "unsloth/gemma-3-4b-it-unsloth-bnb-4bit",
    "unsloth/gemma-3-12b-it-unsloth-bnb-4bit",
    "unsloth/gemma-3-27b-it-unsloth-bnb-4bit",

    # Other popular models!
    "unsloth/Llama-3.1-8B",
    "unsloth/Llama-3.2-3B",
    "unsloth/Llama-3.3-70B",
    "unsloth/mistral-7b-instruct-v0.3",
    "unsloth/Phi-4",
] # More models at https://huggingface.co/unsloth

model, tokenizer = FastModel.from_pretrained(
    model_name = "unsloth/gemma-3-4b-it",
    max_seq_length = 2048, # Choose any for long context!
    load_in_4bit = True,  # 4 bit quantization to reduce memory
    load_in_8bit = False, # [NEW!] A bit more accurate, uses 2x memory
    full_finetuning = False, # [NEW!] We have full finetuning now!
    # token = "hf_...", # use one if using gated models
)

🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.

/scratch/project_2012879/sadiqjun/gemma3/unsloth_env/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Unsloth: Failed to patch Gemma3ForConditionalGeneration.
🦥 Unsloth Zoo will now patch everything to make training faster!
Standard import failed for UnslothRLOOTrainer: No module named 'UnslothRLOOTrainer'. Using tempfile instead!
==((====))==  Unsloth 2025.3.19: Fast Gemma3 patching. Transformers: 4.52.0.dev0.
   \\   /|    Tesla V100-SXM2-32GB. Num GPUs = 1. Max memory: 31.739 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.6.0+cu124. CUDA: 7.0. CUDA Toolkit: 12.4. Triton: 3.2.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.29.post3. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!
Unsloth: Using float16 precision for gemma3 won't work! Using float32.

Using a slow image processor as `use_fast` is unset and a slow processor was saved with this model. `use_fast=True` will be the default behavior in v4.52, even if the model was saved with a slow processor. This will result in minor differences in outputs. You'll still be able to use a slow processor with `use_fast=False`.

We now add LoRA adapters so we only need to update a small amount of parameters!

In [2]:
model = FastModel.get_peft_model(
    model,
    finetune_vision_layers     = False, # Turn off for just text!
    finetune_language_layers   = True,  # Should leave on!
    finetune_attention_modules = True,  # Attention good for GRPO
    finetune_mlp_modules       = True,  # SHould leave on always!

    r = 8,           # Larger = higher accuracy, but might overfit
    lora_alpha = 8,  # Recommended alpha == r at least
    lora_dropout = 0,
    bias = "none",
    random_state = 3407,
)

Unsloth: Making `model.base_model.model.language_model.model` require gradients

In [3]:
from unsloth.chat_templates import get_chat_template
tokenizer = get_chat_template(
    tokenizer,
    chat_template = "gemma-3",
)

In [4]:
#convert json dataset to csv
import json
import pandas as pd

# Load your JSON
with open("final_dataset_combined.json", "r", encoding="utf-8") as f:
    data = json.load(f)

# Turn list-of-dicts into a DataFrame
df = pd.DataFrame(data)

# Save to CSV
df.to_csv("final_dataset_combined.csv", index=False, encoding="utf-8")

print(f"Saved {len(df)} rows with columns {df.columns.tolist()} to final_dataset_combined.csv")

Saved 812 rows with columns ['instruction', 'input', 'output'] to final_dataset_combined.csv

In [5]:
import os, pandas as pd
from datasets import Dataset
from unsloth.chat_templates import standardize_data_formats

# 1) Load the CSV from your notebook folder
file_path = os.path.join(os.getcwd(), "final_dataset_combined.csv")
print("Loading file from:", file_path)

df = pd.read_csv(file_path)
print("Columns in CSV:", df.columns.tolist())  # -> ['instruction','input','output']

# 2) Create a single 'text' column for standardization
df["text"] = df.apply(
    lambda row: f"{row['instruction']} {row['input']} {row['output']}", axis=1
)

# 3) Build a HF Dataset with just that field
dataset = Dataset.from_pandas(df[["text"]])
print("Dataset columns:", dataset.column_names)

# 4) Now you can standardize
print("BEFORE STANDARDIZATION:", dataset[0]["text"][:200])
dataset = standardize_data_formats(dataset)
print("AFTER STANDARDIZATION:", dataset[0]["text"][:200])

# 5) Apply the Gemma-3 chat template to the standardized conversations
def format_with_gemma3(examples):
    # examples["conversations"] is a list of message‐lists for each row
    texts = [
        tokenizer.apply_chat_template(
            conv,
            tokenize=False,
            add_generation_prompt=True
        )
        for conv in examples["conversations"]
    ]
    return {"text": texts}

# Map over the dataset in batched mode to replace "text" with the templated strings
dataset = dataset.map(
    format_with_gemma3,
    batched=True,
    remove_columns=dataset.column_names  # drop old columns (including raw "text" and "conversations")
)

# Quick sanity check:
print("Final templated example:")
print(dataset[100]["text"])

Loading file from: /users/sadiqjun/Thesis/Educhat/LLM_Fine_Tuning/dataset_pipeline/Kiran_univeristy_assistant_pipeline/final_dataset_combined.csv
Columns in CSV: ['instruction', 'input', 'output']
Dataset columns: ['text']
BEFORE STANDARDIZATION: You are Kiran, an AI assistant from Tampere University. Answer the following question from a student based on the provided context: The structure of the course: How does the inclusion of lecture notes
AFTER STANDARDIZATION: You are Kiran, an AI assistant from Tampere University. Answer the following question from a student based on the provided context: The structure of the course: How does the inclusion of lecture notes

Map:   0%|          | 0/812 [00:00<?, ? examples/s]

KeyError: 'conversations'

In [6]:
import os, pandas as pd
from datasets import Dataset

# 1) Load the CSV from your notebook folder
file_path = os.path.join(os.getcwd(), "final_dataset_combined.csv")
print("Loading file from:", file_path)

df = pd.read_csv(file_path)
print("Columns in CSV:", df.columns.tolist())  # -> ['instruction','input','output']

# 2) Create conversation format directly from your instruction/input/output columns
def format_to_conversation(row):
    # Create a proper conversation structure
    conversation = [
        {"role": "user", "content": f"{row['instruction']} {row['input']}"},
        {"role": "assistant", "content": row['output']}
    ]
    return conversation

# 3) Apply the conversation formatting
df["conversations"] = df.apply(format_to_conversation, axis=1)

# 4) Build a HF Dataset with the conversations column
dataset = Dataset.from_pandas(df[["conversations"]])
print("Dataset columns:", dataset.column_names)

# 5) Check the conversation structure
print("Sample conversation structure:")
print(dataset[0]["conversations"])

# 6) Apply the Gemma-3 chat template directly to conversations
def format_with_gemma3(examples):
    texts = []
    for conv in examples["conversations"]:
        formatted_text = tokenizer.apply_chat_template(
            conv,
            tokenize=False,
            add_generation_prompt=False  # Set to False since we have the assistant response
        )
        texts.append(formatted_text)
    return {"text": texts}

# Map over the dataset in batched mode
dataset = dataset.map(
    format_with_gemma3,
    batched=True,
    remove_columns=["conversations"]  # Remove the conversations column, keep only text
)

# Quick sanity check:
print("Final templated example:")
print(dataset[0]["text"])

Loading file from: /users/sadiqjun/Thesis/Educhat/LLM_Fine_Tuning/dataset_pipeline/Kiran_univeristy_assistant_pipeline/final_dataset_combined.csv
Columns in CSV: ['instruction', 'input', 'output']
Dataset columns: ['conversations']
Sample conversation structure:
[{'content': 'You are Kiran, an AI assistant from Tampere University. Answer the following question from a student based on the provided context: The structure of the course: How does the inclusion of lecture notes and readings contribute to the learning objectives in a graduate-level Game Theory course?', 'role': 'user'}, {'content': 'The inclusion of lecture notes and readings in the graduate-level Game Theory course (14.126 at MIT) is structured to align with the advanced learning objectives of the course, which emphasize rigorous analytical training, theoretical depth, and application of game-theoretic models. Lecture notes serve as a foundational resource, distilling complex concepts such as strategic form games, Nash equilibrium, Bayesian games, and repeated games into structured, accessible formats. These notes likely provide step-by-step explanations of mathematical proofs, equilibrium analysis, and solution concepts, enabling students to build technical proficiency and internalize core methodologies. For graduate students, this systematic breakdown is critical for mastering abstract theories and applying them to novel scenarios.  \n\nReadings, often sourced from academic papers or advanced textbooks, complement the lecture notes by exposing students to cutting-edge research, historical developments, and real-world applications. These materials deepen understanding by contextualizing theoretical frameworks within broader economic and strategic problems, such as auction design, mechanism theory, or industrial organization. By engaging with primary literature, students develop critical thinking skills, learn to evaluate empirical evidence, and appreciate the evolution of game-theoretic thought. The combination of lecture notes and readings ensures a dual focus: mastering technical tools while fostering the ability to synthesize and critique scholarly work. This structure prepares students for independent research and advanced problem-solving, aligning with the course’s goal of equipping graduates to contribute meaningfully to economic theory and policy analysis. The absence of explicit examples in the context precludes further specifics, but the general pedagogical role of these resources is clear.', 'role': 'assistant'}]

Map: 100%|██████████| 812/812 [00:00<00:00, 7804.04 examples/s]

Final templated example:
<bos><start_of_turn>user
You are Kiran, an AI assistant from Tampere University. Answer the following question from a student based on the provided context: The structure of the course: How does the inclusion of lecture notes and readings contribute to the learning objectives in a graduate-level Game Theory course?<end_of_turn>
<start_of_turn>model
The inclusion of lecture notes and readings in the graduate-level Game Theory course (14.126 at MIT) is structured to align with the advanced learning objectives of the course, which emphasize rigorous analytical training, theoretical depth, and application of game-theoretic models. Lecture notes serve as a foundational resource, distilling complex concepts such as strategic form games, Nash equilibrium, Bayesian games, and repeated games into structured, accessible formats. These notes likely provide step-by-step explanations of mathematical proofs, equilibrium analysis, and solution concepts, enabling students to build technical proficiency and internalize core methodologies. For graduate students, this systematic breakdown is critical for mastering abstract theories and applying them to novel scenarios.

Readings, often sourced from academic papers or advanced textbooks, complement the lecture notes by exposing students to cutting-edge research, historical developments, and real-world applications. These materials deepen understanding by contextualizing theoretical frameworks within broader economic and strategic problems, such as auction design, mechanism theory, or industrial organization. By engaging with primary literature, students develop critical thinking skills, learn to evaluate empirical evidence, and appreciate the evolution of game-theoretic thought. The combination of lecture notes and readings ensures a dual focus: mastering technical tools while fostering the ability to synthesize and critique scholarly work. This structure prepares students for independent research and advanced problem-solving, aligning with the course’s goal of equipping graduates to contribute meaningfully to economic theory and policy analysis. The absence of explicit examples in the context precludes further specifics, but the general pedagogical role of these resources is clear.<end_of_turn>

In [26]:
from unsloth.chat_templates import standardize_data_formats
dataset = standardize_data_formats(dataset)

We now use `standardize_data_formats` to try converting datasets to the correct format for finetuning purposes!

Let's see how row 100 looks like!

In [7]:
dataset[804]

{'text': '<bos><start_of_turn>user\nYou are Kiran, an AI assistant from Tampere University. Answer the following question from a student based on the provided context: Considering the course’s focus on both technical (e.g., AI, computer science) and humanities-based disciplines (e.g., philosophy, ethics), what potential synergies might emerge in addressing systemic biases in algorithmic systems?<end_of_turn>\n<start_of_turn>model\nThe course "Ethics of AI Bias" at MIT, which bridges technical disciplines like AI and computer science with humanities-based fields such as philosophy and ethics, fosters synergies critical to addressing systemic biases in algorithmic systems. By integrating technical expertise with ethical frameworks, the course enables a multidimensional approach to identifying, analyzing, and mitigating bias.  \n\nFrom the technical perspective, AI and computer science provide tools to detect biases in data, algorithms, and model outputs. For example, algorithmic auditing techniques can quantify disparities in decision-making systems, while fairness-aware machine learning methods aim to correct biased outcomes. However, these technical solutions require ethical guidance to define what constitutes "fairness" or "equity" in specific contexts. Philosophy and ethics contribute by offering conceptual clarity on moral principles, such as justice, responsibility, and human dignity, which inform the design of equitable systems. This interplay ensures that technical interventions align with societal values rather than merely optimizing for superficial metrics like accuracy.  \n\nAdditionally, humanities disciplines help contextualize biases within historical, cultural, and social structures. Systemic biases in algorithms often reflect broader societal inequities, which technical solutions alone cannot resolve. By engaging with philosophical and ethical analysis, developers can better understand the implications of their work and avoid perpetuating harmful stereotypes. For instance, ethical reasoning might challenge the assumption that "neutral" data is inherently unbiased, prompting technical teams to address data collection practices rooted in historical discrimination.  \n\nFinally, collaboration between these fields fosters interdisciplinary education and policy frameworks. Engineers trained in ethical reasoning, and ethicists informed by technical realities, are better equipped to co-design systems that balance innovation with accountability. This synergy is essential for creating algorithmic systems that are not only technically robust but also socially just.<end_of_turn>\n'}

We now have to apply the chat template for `Gemma-3` onto the conversations, and save it to `text`

Let's see how the chat template did! Notice `Gemma-3` default adds a `<bos>`!

In [20]:
# Remove <bos> from your already formatted dataset
def remove_bos(examples):
    texts = [text.removeprefix('<bos>') for text in examples["text"]]
    return {"text": texts}

dataset = dataset.map(remove_bos, batched=True)
print("Removed <bos> tokens from dataset")
print(dataset[100]["text"][:200])

Map: 100%|██████████| 812/812 [00:00<00:00, 77933.57 examples/s]

Removed <bos> tokens from dataset
<start_of_turn>user
You are Kiran, an AI assistant from Tampere University. Answer the following question from a student based on the provided context: How does the Fourier-analytic approach used in t

In [9]:
dataset[330]["text"]

"<bos><start_of_turn>user\nYou are Kiran, an AI assistant from Tampere University. Answer the following question from a student based on the provided context: Analyze the structure and components of a list comprehension that generates nested lists. What are the implications of this structure for data organization and manipulation in Python?<end_of_turn>\n<start_of_turn>model\nA list comprehension in Python is a concise and powerful way to create new lists by iterating over an existing sequence and applying an expression to each element. When generating nested lists using a list comprehension, the structure becomes particularly expressive and useful for organizing and manipulating data in a multidimensional format.\n\nThe basic structure of a list comprehension is as follows:\n\n```\n[expression for element in iterable if condition]\n```\n\nFor generating nested lists, the expression itself can be another list comprehension or a structure that results in a list. For example:\n\n```\n[[expression for inner_element in inner_iterable] for outer_element in outer_iterable]\n```\n\nThis nested structure allows the creation of a list of lists, where each inner list is generated based on the outer loop's element. In the context provided, an example of generating a nested list is given:\n\n```\n[[e, e**2] for e in range(4) if e % 2 != 0]\n```\n\nHere, the outer loop iterates through the `range(4)` values (0, 1, 2, 3), and the condition `if e % 2 != 0` filters the values to include only odd numbers (1 and 3). The inner expression `[e, e**2]` creates a list containing the current element `e` and its square `e**2`. As a result, the final output is a list of lists: `[[1, 1], [3, 9]]`.\n\nThe implications of this structure for data organization and manipulation are significant. Nested lists allow for the representation of complex, hierarchical data structures, such as matrices or grids, which are common in scientific computing, data analysis, and algorithm design. By using list comprehensions to generate these structures, the code becomes more readable and maintainable, as it abstracts away the need for explicit loops and conditionals.\n\nAdditionally, list comprehensions that generate nested lists can be combined with further comprehensions or transformations to perform nested operations efficiently. This structure promotes modularity and reusability, as nested comprehensions can be adapted to different data sources or modified to meet specific data processing needs.\n\nIn summary, list comprehensions that generate nested lists provide a compact and expressive way to create multidimensional data structures in Python. This structure enhances data organization and manipulation, making it a valuable tool for managing complex data in a clean and efficient manner.<end_of_turn>\n"

<a name="Train"></a>
### Train the model
Now let's use Huggingface TRL's `SFTTrainer`! More docs here: [TRL SFT docs](https://huggingface.co/docs/trl/sft_trainer). We do 60 steps to speed things up, but you can set `num_train_epochs=1` for a full run, and turn off `max_steps=None`.

We also use Unsloth's `train_on_completions` method to only train on the assistant outputs and ignore the loss on the user's inputs. This helps increase accuracy of finetunes!

In [10]:
from unsloth.chat_templates import train_on_responses_only
trainer = train_on_responses_only(
    trainer,
    instruction_part = "<start_of_turn>user\n",
    response_part = "<start_of_turn>model\n",
)

NameError: name 'trainer' is not defined

Let's verify masking the instruction part is done! Let's print the 100th row again:

In [58]:
tokenizer.decode(trainer.train_dataset[100]["input_ids"])

'<bos><start_of_turn>user\nYou are Kiran, an AI assistant from Tampere University. Answer the following question from a student based on the provided context:\n\nQuestion: Analyze the process of insertion into a 2-3 tree when a leaf node is full. What are the potential cascading effects up to the root, and how do these operations maintain both the structural and search properties of the tree?<end_of_turn>\n<start_of_turn>model\nThe 2-3 tree insertion process becomes more complex when a leaf node is already full, containing two records. Unlike Binary Search Trees (BSTs), a new child is not simply created downward; instead, a “split-and-promote” operation is initiated.\n\nWhen inserting a new record into a full leaf node (containing two records), the first step is to split this leaf node into two separate nodes. A new node, denoted as L\', is created from free store. The original leaf node (L) receives the record with the smallest key value among the three records. L\' receives the record with the largest key value. The record with the middle key value is then "promoted" up to the parent node, along with a pointer to L\'.\n\nThe effect on the parent node depends on its current state. If the parent node currently contains only one record (and therefore has two children), the promoted record and the pointer to L\' are simply added to the parent. However, if the parent node is also full (containing two records), the split-and-promote process is repeated at the parent node. This means the parent node is split into two, the middle value is promoted to the next level up, and so on.\n\nThis cascading effect can continue all the way up to the root of the tree. If the root node itself becomes full during a promotion, it splits, creating a new root node and increasing the overall height of the tree by one level. This is the only way the height of the tree can increase during insertion.\n\nMaintaining Structural and Search Properties:\n\n*   **Structural Property (Equal Depth of Leaf Nodes):** The split-and-promote operations ensure that all leaf nodes remain at the same depth. Each split creates two nodes at the leaf level, preserving this characteristic. The creation of a new root node when the original root splits also maintains this property.\n*   **Search Property (Ordered Records):** The promotion of the middle key value during the split-and-promote process maintains the ordered nature of the tree. By passing the middle value up, the search property is upheld as the tree continues to organize records in ascending order.\n\n\n\nIn summary, insertion into a 2-3 tree when a leaf is full involves a split-and-promote process that can ripple up to the root, potentially increasing the tree\'s height. This process carefully balances structural changes with the preservation of the tree\'s ordered search property.'

Now let's print the masked out example - you should see only the answer is present:

In [59]:
tokenizer.decode([tokenizer.pad_token_id if x == -100 else x for x in trainer.train_dataset[100]["labels"]]).replace(tokenizer.pad_token, " ")

'                                                                                   The 2-3 tree insertion process becomes more complex when a leaf node is already full, containing two records. Unlike Binary Search Trees (BSTs), a new child is not simply created downward; instead, a “split-and-promote” operation is initiated.\n\nWhen inserting a new record into a full leaf node (containing two records), the first step is to split this leaf node into two separate nodes. A new node, denoted as L\', is created from free store. The original leaf node (L) receives the record with the smallest key value among the three records. L\' receives the record with the largest key value. The record with the middle key value is then "promoted" up to the parent node, along with a pointer to L\'.\n\nThe effect on the parent node depends on its current state. If the parent node currently contains only one record (and therefore has two children), the promoted record and the pointer to L\' are simply added to the parent. However, if the parent node is also full (containing two records), the split-and-promote process is repeated at the parent node. This means the parent node is split into two, the middle value is promoted to the next level up, and so on.\n\nThis cascading effect can continue all the way up to the root of the tree. If the root node itself becomes full during a promotion, it splits, creating a new root node and increasing the overall height of the tree by one level. This is the only way the height of the tree can increase during insertion.\n\nMaintaining Structural and Search Properties:\n\n*   **Structural Property (Equal Depth of Leaf Nodes):** The split-and-promote operations ensure that all leaf nodes remain at the same depth. Each split creates two nodes at the leaf level, preserving this characteristic. The creation of a new root node when the original root splits also maintains this property.\n*   **Search Property (Ordered Records):** The promotion of the middle key value during the split-and-promote process maintains the ordered nature of the tree. By passing the middle value up, the search property is upheld as the tree continues to organize records in ascending order.\n\n\n\nIn summary, insertion into a 2-3 tree when a leaf is full involves a split-and-promote process that can ripple up to the root, potentially increasing the tree\'s height. This process carefully balances structural changes with the preservation of the tree\'s ordered search property.'

In [11]:
# V100-specific training configuration
from trl import SFTTrainer, SFTConfig

trainer = SFTTrainer(
    model = model,
    tokenizer = tokenizer,
    train_dataset = dataset,
    args = SFTConfig(
        dataset_text_field = "text",
        per_device_train_batch_size = 1,  # Reduced for V100 memory
        gradient_accumulation_steps = 8,  # Increased to maintain effective batch size
        warmup_steps = 20,
        num_train_epochs = 3,
        learning_rate = 2e-4,
        logging_steps = 10,
        optim = "adamw_8bit",
        weight_decay = 0.01,
        lr_scheduler_type = "linear",
        seed = 3407,
        report_to = "none",
        output_dir = "./kiran_finetune",
        save_steps = 200,
        save_total_limit = 2,
        dataloader_pin_memory = False,  # Better for V100
        remove_unused_columns = False,  # Prevent column issues
        bf16 = False,  # Explicitly disable bf16
        fp16 = False,  # Explicitly disable fp16 
    ),
)

Unsloth: Switching to float32 training since model cannot work with float16

Unsloth: Tokenizing ["text"] (num_proc=40): 100%|██████████| 812/812 [00:18<00:00, 44.73 examples/s]
Detected kernel version 4.18.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.

In [12]:
from unsloth.chat_templates import train_on_responses_only
trainer = train_on_responses_only(
    trainer,
    instruction_part = "<start_of_turn>user\n",
    response_part = "<start_of_turn>model\n",
)

Map (num_proc=40): 100%|██████████| 812/812 [00:00<00:00, 2095.95 examples/s]

In [13]:
tokenizer.decode(trainer.train_dataset[200]["input_ids"])

'<bos><bos><start_of_turn>user\nYou are Kiran, an AI assistant from Tampere University. Answer the following question from a student based on the provided context: In what sense does an epsilon-regular pair of vertex sets mimic a random bipartite graph, and what does this imply about the distribution of edges within such a pair?<end_of_turn>\n<start_of_turn>model\nAn epsilon-regular pair of vertex sets in a graph mimics a random bipartite graph in terms of how the edges are distributed between the two sets. Specifically, for a pair of vertex sets $ X $ and $ Y $ to be epsilon-regular, the edge density between any two sufficiently large subsets $ A \\subseteq X $ and $ B \\subseteq Y $ must be close to the overall edge density between $ X $ and $ Y $. In other words, if you randomly pick subsets $ A $ and $ B $ from $ X $ and $ Y $, the number of edges between them should not deviate significantly from what you would expect in a truly random bipartite graph with the same edge density.\n\nThis condition implies that the distribution of edges is uniform in a precise mathematical sense. In a random bipartite graph, the number of edges between any two large subsets of the vertex sets is close to the expected value determined by the overall density. Similarly, in an epsilon-regular pair, the edge distribution is such that no "local" fluctuations in density exist—there are no regions where the graph is significantly denser or sparser compared to the overall density. This uniformity ensures that the pair behaves like a random graph in terms of edge distribution, even though it may not be truly random.\n\nThe epsilon-regularity condition is crucial in Szemerédi’s graph regularity lemma, as it allows us to approximate a large graph by a small number of such random-like bipartite graphs. This approximation is powerful because it simplifies the structure of the graph, making it amenable to analysis and application in various graph-theoretic problems.<end_of_turn>\n'

In [35]:
tokenizer.decode([tokenizer.pad_token_id if x == -100 else x for x in trainer.train_dataset[100]["labels"]]).replace(tokenizer.pad_token, " ")

"                                                                                             The Fourier-analytic approach in the proof of Bogolyubov's lemma uses the size of Fourier coefficients to extract a large subspace within $ 2A - 2A $ by distinguishing between large and small Fourier coefficients. The set $ A $, being a subset of $ \\mathbb{F}_2^n $ with density $ \\alpha $, has a convolution $ f = 1_A * 1_A * 1_A * 1_A $ (or $ 2A - 2A $) whose support is the sumset $ 2A - 2A $. The Fourier transform of $ f $ is given by $ \\widehat{f}(\\xi) = |\\widehat{1_A}(\\xi)|^4 $, and its inverse Fourier transform allows the evaluation of $ f(x) $ in terms of the Fourier coefficients of $ 1_A $.\n\nTo construct a large subspace within $ 2A - 2A $, the proof defines a set $ R $ consisting of all Fourier characters $ \\xi $ for which $ |\\widehat{1_A}(\\xi)| \\geq \\alpha^{3/2} $. This threshold $ \\alpha^{3/2} $ is critical because it ensures that the number of such characters is small. By Parseval's identity, the sum of the squares of the Fourier coefficients equals the $ L^2 $-norm of $ 1_A $, which is $ \\alpha $. Thus, the number of characters in $ R $ is at most $ 1/\\alpha^2 $, as the sum of the squares of the large coefficients cannot exceed $ \\alpha $.\n\nThe orthogonal complement $ R^\\perp $ is a subspace of $ \\mathbb{F}_2^n $, and it is shown that $ f $ is positive on $ R^\\perp $. This is achieved by evaluating $ f(x) $ for $ x \\in R^\\perp $ using the Fourier inversion formula. The main term in the sum is $ \\alpha^4 $, and the contributions from the remaining Fourier coefficients are small, ensuring that $ f(x) $ remains positive. As a result, $ R^\\perp $ is contained in the support of $ f $, which is $ 2A - 2A $.\n\nThe threshold $ \\alpha^{3/2} $ thus plays a central role in defining the set $ R $, ensuring it is small and that its orthogonal complement $ R^\\perp $ is large (with codimension at most $ 1/\\alpha^2 $) and lies within $ 2A - 2A $. This construction guarantees the existence of a large subspace within the iterated sumset, leveraging the interplay between Fourier analysis and the size of the Fourier coefficients.<end_of_turn>\n"

In [36]:
# @title Show current memory stats
gpu_stats = torch.cuda.get_device_properties(0)
start_gpu_memory = round(torch.cuda.max_memory_reserved() / 1024 / 1024 / 1024, 3)
max_memory = round(gpu_stats.total_memory / 1024 / 1024 / 1024, 3)
print(f"GPU = {gpu_stats.name}. Max memory = {max_memory} GB.")
print(f"{start_gpu_memory} GB of memory reserved.")

GPU = Tesla V100-SXM2-32GB. Max memory = 31.739 GB.
14.152 GB of memory reserved.

In [37]:
# @title Show current memory stats
import torch # Make sure torch is imported

# Get GPU properties
gpu_stats = torch.cuda.get_device_properties(0)
max_memory_gb = round(gpu_stats.total_memory / 1024**3, 3) # Use 1024**3 for GiB

# Get current memory usage
# memory_allocated: Memory actively used by tensors
current_memory_allocated_gb = round(torch.cuda.memory_allocated(0) / 1024**3, 3)
# memory_reserved: Total memory managed by PyTorch's caching allocator (allocated + cached but free)
current_memory_reserved_gb = round(torch.cuda.memory_reserved(0) / 1024**3, 3)

# Get peak memory usage *so far* since the start or last reset_peak_stats()
peak_memory_reserved_gb = round(torch.cuda.max_memory_reserved(0) / 1024**3, 3)

print(f"GPU = {gpu_stats.name}. Max memory = {max_memory_gb} GB.")
print(f"Currently Allocated = {current_memory_allocated_gb} GB.")
print(f"Currently Reserved  = {current_memory_reserved_gb} GB.")
print(f"Peak Reserved (so far) = {peak_memory_reserved_gb} GB.")

# You can optionally reset the peak stats if you want to measure peak usage for a specific section
# torch.cuda.reset_peak_memory_stats(0)

GPU = Tesla V100-SXM2-32GB. Max memory = 31.739 GB.
Currently Allocated = 4.667 GB.
Currently Reserved  = 4.834 GB.
Peak Reserved (so far) = 14.152 GB.

Let's train the model! To resume a training run, set `trainer.train(resume_from_checkpoint = True)`

In [42]:
# Your dataset is already properly formatted, so use it directly
print("Dataset is already properly formatted!")
print("Sample:", dataset[0]["text"][:200], "...")

Dataset is already properly formatted!
Sample: <start_of_turn>user
You are Kiran, an AI assistant from Tampere University. Answer the following question from a student based on the provided context: The structure of the course: How does the inclus ...

In [45]:
# Check the structure of your dataset
print("Dataset type:", type(dataset))
print("Dataset length:", len(dataset))
print("Dataset columns:", dataset.column_names)
print("\nFirst example:")
print("Type of text field:", type(dataset[0]['text']))
print("Text content:", repr(dataset[0]['text']))

Dataset type: <class 'datasets.arrow_dataset.Dataset'>
Dataset length: 812
Dataset columns: ['text']

First example:
Type of text field: <class 'str'>
Text content: '<start_of_turn>user\nYou are Kiran, an AI assistant from Tampere University. Answer the following question from a student based on the provided context: The structure of the course: How does the inclusion of lecture notes and readings contribute to the learning objectives in a graduate-level Game Theory course?<end_of_turn>\n<start_of_turn>model\nThe inclusion of lecture notes and readings in the graduate-level Game Theory course (14.126 at MIT) is structured to align with the advanced learning objectives of the course, which emphasize rigorous analytical training, theoretical depth, and application of game-theoretic models. Lecture notes serve as a foundational resource, distilling complex concepts such as strategic form games, Nash equilibrium, Bayesian games, and repeated games into structured, accessible formats. These notes likely provide step-by-step explanations of mathematical proofs, equilibrium analysis, and solution concepts, enabling students to build technical proficiency and internalize core methodologies. For graduate students, this systematic breakdown is critical for mastering abstract theories and applying them to novel scenarios.  \n\nReadings, often sourced from academic papers or advanced textbooks, complement the lecture notes by exposing students to cutting-edge research, historical developments, and real-world applications. These materials deepen understanding by contextualizing theoretical frameworks within broader economic and strategic problems, such as auction design, mechanism theory, or industrial organization. By engaging with primary literature, students develop critical thinking skills, learn to evaluate empirical evidence, and appreciate the evolution of game-theoretic thought. The combination of lecture notes and readings ensures a dual focus: mastering technical tools while fostering the ability to synthesize and critique scholarly work. This structure prepares students for independent research and advanced problem-solving, aligning with the course’s goal of equipping graduates to contribute meaningfully to economic theory and policy analysis. The absence of explicit examples in the context precludes further specifics, but the general pedagogical role of these resources is clear.<end_of_turn>\n'

In [ ]:
from trl import SFTTrainer, SFTConfig
import os


# Apply response masking
from unsloth.chat_templates import train_on_responses_only
trainer = train_on_responses_only(
    trainer,
    instruction_part = "<start_of_turn>user\n",
    response_part = "<start_of_turn>model\n",
)

# Train with these settings
print("Starting training...")
trainer_stats = trainer.train()
print("Training complete")

# Save the trained model
print(f"Saving trained model to: {output_dir}")
model.save_pretrained(output_dir)
tokenizer.save_pretrained(output_dir)

In [43]:
trainer_stats = trainer.train()

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 812 | Num Epochs = 3 | Total steps = 303
O^O/ \_/ \    Batch size per device = 1 | Gradient accumulation steps = 8
\        /    Data Parallel GPUs = 1 | Total batch size (1 x 8 x 1) = 8
 "-____-"     Trainable parameters = 14,901,248/4,000,000,000 (0.37% trained)

ValueError: Unable to create tensor, you should probably activate truncation and/or padding with 'padding=True' 'truncation=True' to have batched tensors with the same length. Perhaps your features (`text` in this case) have excessive nesting (inputs type `list` where type `int` is expected).

In [3]:
# @title Show current memory stats
import torch # Make sure torch is imported

# Get GPU properties
gpu_stats = torch.cuda.get_device_properties(0)
max_memory_gb = round(gpu_stats.total_memory / 1024**3, 3) # Use 1024**3 for GiB

# Get current memory usage
# memory_allocated: Memory actively used by tensors
current_memory_allocated_gb = round(torch.cuda.memory_allocated(0) / 1024**3, 3)
# memory_reserved: Total memory managed by PyTorch's caching allocator (allocated + cached but free)
current_memory_reserved_gb = round(torch.cuda.memory_reserved(0) / 1024**3, 3)

# Get peak memory usage *so far* since the start or last reset_peak_stats()
peak_memory_reserved_gb = round(torch.cuda.max_memory_reserved(0) / 1024**3, 3)

print(f"GPU = {gpu_stats.name}. Max memory = {max_memory_gb} GB.")
print(f"Currently Allocated = {current_memory_allocated_gb} GB.")
print(f"Currently Reserved  = {current_memory_reserved_gb} GB.")
print(f"Peak Reserved (so far) = {peak_memory_reserved_gb} GB.")

# You can optionally reset the peak stats if you want to measure peak usage for a specific section
# torch.cuda.reset_peak_memory_stats(0)

GPU = Tesla V100-SXM2-32GB. Max memory = 31.739 GB.
Currently Allocated = 5.787 GB.
Currently Reserved  = 5.852 GB.
Peak Reserved (so far) = 6.998 GB.

<a name="Inference"></a>
### Inference
Let's run the model via Unsloth native inference! According to the `Gemma-3` team, the recommended settings for inference are `temperature = 1.0, top_p = 0.95, top_k = 64`

In [63]:
from unsloth.chat_templates import get_chat_template
tokenizer = get_chat_template(
    tokenizer,
    chat_template = "gemma-3",
)
messages = [{
    "role": "user",
    "content": [{
        "type" : "text",
        "text" : "Continue the sequence: 1, 1, 2, 3, 5, 8,",
    }]
}]
text = tokenizer.apply_chat_template(
    messages,
    add_generation_prompt = True, # Must add for generation
)
outputs = model.generate(
    **tokenizer([text], return_tensors = "pt").to("cuda"),
    max_new_tokens = 64, # Increase for longer outputs!
    # Recommended Gemma-3 settings!
    temperature = 1.0, top_p = 0.95, top_k = 64,
)
tokenizer.batch_decode(outputs)

['<bos><start_of_turn>user\nContinue the sequence: 1, 1, 2, 3, 5, 8,<end_of_turn>\n<start_of_turn>model\nThe sequence 1, 1, 2, 3, 5, 8, ... is the Fibonacci sequence. In this sequence, each number is the sum of the two preceding ones.\n\nTo continue the sequence, we add the last two numbers:\n\n*   5 + 8 = 1']

 You can also use a `TextStreamer` for continuous inference - so you can see the generation token by token, instead of waiting the whole time!

In [64]:
messages = [{
    "role": "user",
    "content": [{"type": "text", "text": "who are you"}]
}]

text = tokenizer.apply_chat_template(
    messages,
    add_generation_prompt=True,
)

from transformers import TextStreamer
_ = model.generate(
    **tokenizer([text], return_tensors="pt").to("cuda"),
    max_new_tokens=512,  # Increased to allow for a comprehensive answer
    temperature=0.7,  # Slightly reduced for more factual responses
    top_p=0.95,
    top_k=50,
    streamer=TextStreamer(tokenizer, skip_prompt=True),
)

I'm Gemma, an open-weights AI assistant. I'm a large language model created by the Gemma team at Google DeepMind. I'm available in both open-weight and demo modes. I can take text and images as input and respond in text. Because I am an open-weight model, I am widely available to the public.
<end_of_turn>

In [65]:
# ... (identity_examples and dataset creation code remains the same) ...
import os # Make sure os is imported

# Define the output path in your scratch directory
output_base_path = "/scratch/project_2012879/sadiqjun/gemma3" # Your project dir
output_dir = os.path.join(output_base_path, "kiran_identity_fixed_scratch") # Use a new name or the same name in scratch
print(f"Trainer output and final model will be saved to: {output_dir}")

# Fine-tune with stronger settings
from trl import SFTTrainer, SFTConfig
trainer = SFTTrainer(
    model = model,
    tokenizer = tokenizer,
    train_dataset = larger_identity_dataset, # Make sure this is the correct dataset variable
    args = SFTConfig(
        dataset_text_field = "text",
        per_device_train_batch_size = 1,
        gradient_accumulation_steps = 4,
        num_train_epochs = 20,  # More epochs
        learning_rate = 5e-4,  # Higher learning rate
        optim = "adamw_8bit",
        # **** CHANGE THIS ****
        output_dir = output_dir,
        save_steps = 10, # Checkpoint saving path is now in scratch
    ),
)

print("Starting training...")
trainer.train()
print("Training finished.")

# **** CHANGE THESE ****
print(f"Saving final model and tokenizer to: {output_dir}")
model.save_pretrained(output_dir)
tokenizer.save_pretrained(output_dir)
print("Model and tokenizer saved.")

Trainer output and final model will be saved to: /scratch/project_2012879/sadiqjun/gemma3/kiran_identity_fixed_scratch
Unsloth: Switching to float32 training since model cannot work with float16

num_proc must be <= 25. Reducing num_proc to 25 for dataset of size 25.
Unsloth: Tokenizing ["text"] (num_proc=25): 100%|██████████| 25/25 [00:11<00:00,  2.20 examples/s]
Detected kernel version 4.18.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.

Starting training...

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 25 | Num Epochs = 20 | Total steps = 120
O^O/ \_/ \    Batch size per device = 1 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (1 x 4 x 1) = 4
 "-____-"     Trainable parameters = 59,604,992/4,000,000,000 (1.49% trained)

Training finished.
Saving final model and tokenizer to: /scratch/project_2012879/sadiqjun/gemma3/kiran_identity_fixed_scratch
Model and tokenizer saved.

<a name="Save"></a>
### Saving, loading finetuned models
To save the final model as LoRA adapters, either use Huggingface's `push_to_hub` for an online save or `save_pretrained` for a local save.

**[NOTE]** This ONLY saves the LoRA adapters, and not the full model. To save to 16bit or GGUF, scroll down!

In [4]:
# Test the identity with different prompts
identity_tests = [
    "Who are you?",
    "What's your name?",
    "Are you Gemma or Kiran?",
    "Tell me about yourself."
]

for test in identity_tests:
    print(f"\n\n=== Testing: '{test}' ===\n")

    messages = [{
        "role": "user",
        "content": [{"type": "text", "text": test}]
    }]

    text = tokenizer.apply_chat_template(
        messages,
        add_generation_prompt=True,
    )

    _ = model.generate(
        **tokenizer([text], return_tensors="pt").to("cuda"),
        max_new_tokens=256,
        temperature=0.7,
        top_p=0.95,
        top_k=50,
        streamer=TextStreamer(tokenizer, skip_prompt=True),
    )

=== Testing: 'Who are you?' ===

NameError: name 'TextStreamer' is not defined

In [5]:
from datasets import load_dataset
import os # Make sure os is imported

# Define a cache directory in your scratch space
scratch_cache_dir = "/scratch/project_2012879/sadiqjun/gemma3/hf_datasets_cache"
print(f"Using Hugging Face datasets cache directory: {scratch_cache_dir}")

# Load GSM8K dataset (main version), specifying the cache directory
gsm8k = load_dataset(
    "gsm8k",
    "main",
    cache_dir=scratch_cache_dir # <<< ADD THIS ARGUMENT
)

# Check dataset contents
print(f"GSM8K training set size: {len(gsm8k['train'])} examples")
print(f"GSM8K test set size: {len(gsm8k['test'])} examples")

# Display sample
print("\nSample GSM8K problem:")
print(f"Question: {gsm8k['train'][0]['question']}")
print(f"Answer: {gsm8k['train'][0]['answer']}")

Using Hugging Face datasets cache directory: /scratch/project_2012879/sadiqjun/gemma3/hf_datasets_cache
GSM8K training set size: 7473 examples
GSM8K test set size: 1319 examples

Sample GSM8K problem:
Question: Natalia sold clips to 48 of her friends in April, and then she sold half as many clips in May. How many clips did Natalia sell altogether in April and May?
Answer: Natalia sold 48/2 = <<48/2=24>>24 clips in May.
Natalia sold 48+24 = <<48+24=72>>72 clips altogether in April and May.
#### 72

In [6]:
# Function to extract just the final answer from GSM8K problems (removes step-by-step reasoning)
def extract_gsm8k_final_answer(answer_text):
    # GSM8K answers typically end with "The answer is X" or similar
    # Extract just that final line or the numerical answer
    lines = answer_text.strip().split('\n')
    last_line = lines[-1]

    # If the last line has "The answer is" or similar, return that
    if "answer is" in last_line.lower() or "=" in last_line:
        return last_line
    # Otherwise just return numerical value
    import re
    numbers = re.findall(r'\d+', last_line)
    if numbers:
        return f"The answer is {numbers[-1]}"
    # Fallback to the original answer
    return answer_text

# Format GSM8K for Kiran's identity - OPTION 1: WITH reasoning (original dataset value)
def format_gsm8k_with_reasoning(example):
    return {
        "text": f"<start_of_turn>system\nYou are Kiran, an AI assistant from Tampere University.\n<end_of_turn>\n<start_of_turn>user\nSolve this math problem: {example['question']}\n<end_of_turn>\n<start_of_turn>assistant\n{example['answer']}\n<end_of_turn>"
    }

# Format GSM8K for Kiran's identity - OPTION 2: WITHOUT reasoning (per your request)
def format_gsm8k_without_reasoning(example):
    final_answer = extract_gsm8k_final_answer(example['answer'])
    return {
        "text": f"<start_of_turn>system\nYou are Kiran, an AI assistant from Tampere University.\n<end_of_turn>\n<start_of_turn>user\nSolve this math problem: {example['question']}\n<end_of_turn>\n<start_of_turn>assistant\n{final_answer}\n<end_of_turn>"
    }

# Apply the formatting - CHOOSE ONE based on your preference
math_dataset_with_reasoning = gsm8k["train"].map(format_gsm8k_with_reasoning)
# OR
math_dataset_without_reasoning = gsm8k["train"].map(format_gsm8k_without_reasoning)

# Sample to verify the formatting
print("\nWith reasoning:")
print(math_dataset_with_reasoning[0]['text'][:300] + "...")
print("\nWithout reasoning:")
print(math_dataset_without_reasoning[0]['text'][:300] + "...")

Map: 100%|██████████| 7473/7473 [00:00<00:00, 13682.65 examples/s]
Map: 100%|██████████| 7473/7473 [00:00<00:00, 23374.62 examples/s]

With reasoning:
<start_of_turn>system
You are Kiran, an AI assistant from Tampere University.
<end_of_turn>
<start_of_turn>user
Solve this math problem: Natalia sold clips to 48 of her friends in April, and then she sold half as many clips in May. How many clips did Natalia sell altogether in April and May?
<end_of...

Without reasoning:
<start_of_turn>system
You are Kiran, an AI assistant from Tampere University.
<end_of_turn>
<start_of_turn>user
Solve this math problem: Natalia sold clips to 48 of her friends in April, and then she sold half as many clips in May. How many clips did Natalia sell altogether in April and May?
<end_of...

In [7]:
import random
from datasets import load_dataset
import os # Make sure os is imported

# Define a cache directory in your scratch space (can be the same one as before)
scratch_cache_dir = "/scratch/project_2012879/sadiqjun/gemma3/hf_datasets_cache"
print(f"Using Hugging Face datasets cache directory: {scratch_cache_dir}")

# Load GSM8K dataset, specifying the cache directory
gsm8k = load_dataset(
    "gsm8k",
    "main",
    cache_dir=scratch_cache_dir # <<< ADD THIS ARGUMENT
)
print(f"Loaded GSM8K with {len(gsm8k['train'])} training examples")

# Create a balanced sample
math_sample_size = 7473  # Same size as code subset for balance
math_indices = random.sample(range(len(gsm8k['train'])), math_sample_size)
math_subset = gsm8k['train'].select(math_indices)

print(f"Created math subset with {len(math_subset)} examples")

Using Hugging Face datasets cache directory: /scratch/project_2012879/sadiqjun/gemma3/hf_datasets_cache
Loaded GSM8K with 7473 training examples
Created math subset with 7473 examples

In [8]:
# Load the dataset and check what splits are available
from datasets import load_dataset
import os # Make sure os is imported

# Define a cache directory in your scratch space (can be the same one as before)
scratch_cache_dir = "/scratch/project_2012879/sadiqjun/gemma3/hf_datasets_cache"
print(f"Using Hugging Face datasets cache directory: {scratch_cache_dir}")

# Load the dataset using a specific configuration (split_0), specifying the cache directory
nvidia_code = load_dataset(
    "nvidia/OpenCodeReasoning",
    "split_0",
    cache_dir=scratch_cache_dir # <<< ADD THIS ARGUMENT
)

# Check what splits are available (should just be 'split_0' based on your previous output)
print(f"Available splits in NVIDIA dataset configuration 'split_0': {list(nvidia_code.keys())}")

# Print first few examples to understand structure
split_name = list(nvidia_code.keys())[0]  # Use the first available split
print(f"\nUsing split: '{split_name}'")
print(f"Number of examples: {len(nvidia_code[split_name])}")
print(f"Dataset columns: {nvidia_code[split_name].column_names}")
print(f"\nSample problem structure:")
sample = nvidia_code[split_name][0]
for key, value in sample.items():
    if isinstance(value, str):
        print(f"{key}: {value[:100]}..." if len(value) > 100 else f"{key}: {value}")
    else:
        print(f"{key}: {type(value)}")

Using Hugging Face datasets cache directory: /scratch/project_2012879/sadiqjun/gemma3/hf_datasets_cache
Available splits in NVIDIA dataset configuration 'split_0': ['split_0']

Using split: 'split_0'
Number of examples: 567850
Dataset columns: ['id', 'input', 'output', 'source', 'license', 'dataset', 'split', 'difficulty', 'solution']

Sample problem structure:
id: c0d4209f929db2b5bf3526a47a2520b0
input: Problem description.
Vipul is a hardworking super-hero who maintains the bracket ratio of all the st...
output: <think>
Okay, I need to solve this problem where I have to check if the brackets in a string are bal...
source: codechef
license: cc-by-4.0
dataset: code_contests
split: train
difficulty: UNKNOWN_DIFFICULTY
solution: T = int(input())
for _ in range(T):
    s = input().strip()
    stack = []
    valid = True
    for ...

In [9]:
# Create a smaller subset of the large dataset
import random
random.seed(42)
code_sample_size = 10000  # Adjust based on your time/resource constraints
# Sample from the dataset
indices = random.sample(range(len(nvidia_code["split_0"])), code_sample_size)
code_subset = nvidia_code["split_0"].select(indices)
print(f"Loaded nvidia_code with {len(nvidia_code['split_0'])} training examples") # Changed "split_0" to 'split_0'

print(f"Created code subset with {len(code_subset)} examples")

Loaded nvidia_code with 567850 training examples
Created code subset with 10000 examples

Now if you want to load the LoRA adapters we just saved for inference, set `False` to `True`:

In [10]:
# Format the code dataset for Kiran
def format_code_examples(example):
    # Extract problem description and solution
    problem = example['input']
    solution = example['solution']

    # Format with Kiran identity
    return {
        "text": f"<start_of_turn>system\nYou are Kiran, an AI assistant from Tampere University.\n<end_of_turn>\n<start_of_turn>user\nImplement code for this problem: {problem}\n<end_of_turn>\n<start_of_turn>assistant\n```python\n{solution}\n```\n<end_of_turn>"
    }

# Format the math dataset for Kiran
def format_math_examples(example):
    # If you want final answer only (without reasoning)
    answer_parts = example['answer'].strip().split('\n')
    final_answer = answer_parts[-1]

    # Format with Kiran identity
    return {
        "text": f"<start_of_turn>system\nYou are Kiran, an AI assistant from Tampere University.\n<end_of_turn>\n<start_of_turn>user\nSolve this math problem: {example['question']}\n<end_of_turn>\n<start_of_turn>assistant\n{final_answer}\n<end_of_turn>"
    }

# Apply formatting to both datasets
formatted_code = code_subset.map(format_code_examples)
formatted_math = math_subset.map(format_math_examples)

# Verify formatting with samples
print("\nCode example format:")
print(formatted_code[0]['text'][:200] + "...")

print("\nMath example format:")
print(formatted_math[0]['text'][:200] + "...")

Code example format:
<start_of_turn>system
You are Kiran, an AI assistant from Tampere University.
<end_of_turn>
<start_of_turn>user
Implement code for this problem: A tree is an undirected connected graph without cycles....

Math example format:
<start_of_turn>system
You are Kiran, an AI assistant from Tampere University.
<end_of_turn>
<start_of_turn>user
Solve this math problem: A man is returning home from work and trying to decide which ro...

In [11]:
from datasets import concatenate_datasets

# --- Formatting Functions ---
# Adjust these based on the exact column names and desired prompt structure

def format_math_example(example):
    # Example assumes 'question' and 'answer' columns in math_subset
    # Use the same prompt structure as your initial fine-tuning
    user_prompt = f"Solve the following math problem:\n\nQuestion: {example['question']}"
    model_response = example['answer']
    # Use the tokenizer's chat template application if available and preferred,
    # otherwise, manually construct the string.
    # Example manual construction:
    formatted_text = f"<start_of_turn>user\n{user_prompt}<end_of_turn>\n<start_of_turn>model\n{model_response}<end_of_turn>"
    return {"text": formatted_text}

def format_code_example(example):
    # Example assumes 'input' and 'solution' columns in code_subset
    # Use the same prompt structure as your initial fine-tuning
    user_prompt = f"Write code to solve the following problem:\n\nProblem: {example['input']}"
    model_response = example['solution']
    # Example manual construction:
    formatted_text = f"<start_of_turn>user\n{user_prompt}<end_of_turn>\n<start_of_turn>model\n{model_response}<end_of_turn>"
    return {"text": formatted_text}

# --- Apply Formatting ---
# Ensure subsets exist and have expected columns before mapping
if 'math_subset' in locals() and math_subset:
    print("Formatting math subset...")
    formatted_math = math_subset.map(format_math_example, remove_columns=math_subset.column_names)
else:
    print("Math subset not found or empty.")
    formatted_math = None

if 'code_subset' in locals() and code_subset:
    print("Formatting code subset...")
    formatted_code = code_subset.map(format_code_example, remove_columns=code_subset.column_names)
else:
    print("Code subset not found or empty.")
    formatted_code = None

# --- Concatenate Datasets ---
datasets_to_combine = []
if formatted_math:
    datasets_to_combine.append(formatted_math)
    print(f"Formatted math subset has {len(formatted_math)} examples.")
if formatted_code:
    datasets_to_combine.append(formatted_code)
    print(f"Formatted code subset has {len(formatted_code)} examples.")

if len(datasets_to_combine) > 0:
    combined_dataset = concatenate_datasets(datasets_to_combine)
    # Optional: Shuffle the combined dataset
    combined_dataset = combined_dataset.shuffle(seed=42)
    print(f"\nCombined dataset created with {len(combined_dataset)} examples.")
    print(f"Columns: {combined_dataset.column_names}")
    # Display a sample from the combined dataset
    print("\nSample from combined dataset:")
    print(combined_dataset[0]['text'][:500] + "...") # Print first 500 chars
else:
    print("\nError: No formatted datasets available to combine.")
    combined_dataset = None # Ensure variable exists but is None

Formatting math subset...
Formatting code subset...
Formatted math subset has 7473 examples.
Formatted code subset has 10000 examples.

Combined dataset created with 17473 examples.
Columns: ['text']

Sample from combined dataset:
<start_of_turn>user
Solve the following math problem:

Question: Jon's laundry machine can do 5 pounds of laundry at a time.  4 shirts weigh 1 pound and 2 pairs of pants weigh 1 pound.  If he needs to wash 20 shirts and 20 pants, how many loads of laundry does he have to do?<end_of_turn>
<start_of_turn>model
The shirts weigh 20/4=<<20/4=5>>5 pounds
The pants weigh 20/2=<<20/2=10>>10 pounds
So he needs to do 10+5=<<10+5=15>>15 pounds of laundry
So that would take 15/5=<<15/5=3>>3 loads of laundry...

In [13]:
from unsloth import FastModel # Or FastLanguageModel
import torch
from peft import PeftModel # Import PeftModel

# --- Load the Base Model AGAIN ---
# Use the same settings as your initial successful QLoRA load
print("Loading base model...")
model, tokenizer = FastModel.from_pretrained(
    model_name = "google/gemma-3-4b-it",
    max_seq_length = 2048,
    load_in_4bit = True, # Keep this for QLoRA
    token = "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", # Optional
)
print("Base model loaded.")

# --- Manually Cast lm_head AGAIN (Important!) ---
# The base model loading resets this, so we need to re-apply the fix
try:
    target_lm_head = model.base_model.lm_head
    target_lm_head = target_lm_head.to(torch.float32)
    model.base_model.lm_head = target_lm_head
    print(f"Manually cast lm_head dtype to: {model.base_model.lm_head.weight.dtype}")
except AttributeError as e:
    print(f"Error casting lm_head: {e}. Check model structure.")


# --- Load the LoRA Adapters ---
adapter_path = "/scratch/project_2012879/sadiqjun/gemma3/kiran_identity_fixed_scratch" # Path where you saved the first finetune
print(f"Loading LoRA adapters from: {adapter_path}")

# Use PeftModel.from_pretrained to load adapters onto the base model
# Make sure is_trainable=True if you want to continue training these adapters
model = PeftModel.from_pretrained(model, adapter_path, is_trainable=True)

print("LoRA adapters loaded onto the base model.")
# Optional: Verify trainable parameters again
model.print_trainable_parameters()

Loading base model...
==((====))==  Unsloth 2025.3.19: Fast Gemma3 patching. Transformers: 4.52.0.dev0.
   \\   /|    Tesla V100-SXM2-32GB. Num GPUs = 1. Max memory: 31.739 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.6.0+cu124. CUDA: 7.0. CUDA Toolkit: 12.4. Triton: 3.2.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.29.post3. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!
Unsloth: Using float16 precision for gemma3 won't work! Using float32.
Base model loaded.
Manually cast lm_head dtype to: torch.float32
Loading LoRA adapters from: /scratch/project_2012879/sadiqjun/gemma3/kiran_identity_fixed_scratch
LoRA adapters loaded onto the base model.
trainable params: 59,604,992 || all params: 4,359,684,464 || trainable%: 1.3672

In [17]:
from trl import SFTTrainer, SFTConfig
import os

# Define a NEW output directory for this stage of training
output_base_path_stage2 = "/scratch/project_2012879/sadiqjun/gemma3"
output_dir_stage2 = os.path.join(output_base_path_stage2, "kiran_math_code_finetune")
print(f"Stage 2 Trainer output will be saved to: {output_dir_stage2}")

# Check if combined_dataset exists and is not empty
if combined_dataset and len(combined_dataset) > 0:
    trainer_stage2 = SFTTrainer(
        model = model, # Model with adapters loaded
        tokenizer = tokenizer,
        train_dataset = combined_dataset, # Use the combined dataset
        args = SFTConfig(
            output_dir = output_dir_stage2, # New output directory
            dataset_text_field = "text",

            # Adjust training parameters as needed for this stage
            per_device_train_batch_size = 1, # Keep batch size low due to memory
            gradient_accumulation_steps = 8, # Can increase accumulation
            num_train_epochs = 1, # Train for 1-3 epochs on the new data
            learning_rate = 1e-5, # Use a LOWER learning rate for continued fine-tuning
            logging_steps = 20,
            optim = "adamw_8bit",
            save_steps = 100, # Adjust based on total steps: ceil(len(combined_dataset) / (1*8)) * num_epochs
            save_total_limit = 2,
            seed = 42, # Use a different seed or the same one
            report_to = "none",
            # Add other necessary args like weight_decay, lr_scheduler_type if needed
        ),
    )

    print("Attempting to resume Stage 2 training from checkpoint...") # Changed print message
    # **** MODIFY THIS LINE ****
    trainer_stage2.train(resume_from_checkpoint=True)
    print("Stage 2 training finished (or resumed and finished).")

    # Save the final adapters from this stage
    print(f"Saving final Stage 2 model and tokenizer to: {output_dir_stage2}")
    model.save_pretrained(output_dir_stage2)
    tokenizer.save_pretrained(output_dir_stage2)
    print("Stage 2 Model and tokenizer saved.")

else:
    print("Skipping Stage 2 training as combined_dataset is not valid.")

Stage 2 Trainer output will be saved to: /scratch/project_2012879/sadiqjun/gemma3/kiran_math_code_finetune
Unsloth: Switching to float32 training since model cannot work with float16

Unsloth: Tokenizing ["text"] (num_proc=40): 100%|██████████| 17473/17473 [00:19<00:00, 892.24 examples/s]
Detected kernel version 4.18.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.

Attempting to resume Stage 2 training from checkpoint...

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 17,473 | Num Epochs = 1 | Total steps = 2,184
O^O/ \_/ \    Batch size per device = 1 | Gradient accumulation steps = 8
\        /    Data Parallel GPUs = 1 | Total batch size (1 x 8 x 1) = 8
 "-____-"     Trainable parameters = 59,604,992/4,000,000,000 (1.49% trained)

Stage 2 training finished (or resumed and finished).
Saving final Stage 2 model and tokenizer to: /scratch/project_2012879/sadiqjun/gemma3/kiran_math_code_finetune
Stage 2 Model and tokenizer saved.

In [20]:
from unsloth import FastLanguageModel # Use FastLanguageModel for inference features
import torch

# --- Configuration ---
max_seq_length = 2048 # Use the same max_seq_length
final_adapter_path = "/scratch/project_2012879/sadiqjun/gemma3/kiran_math_code_finetune" # Path to your FINAL adapters

# --- Load the Base Model and Merge Adapters ---
# Load the base model in 4bit.
# Pass `device_map="auto"` for Unsloth to handle placement.
# IMPORTANT: Load directly with FastLanguageModel for inference optimizations.
print("Loading base model for inference...")
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = final_adapter_path, # <<<<<< LOAD DIRECTLY FROM FINAL ADAPTER PATH
    max_seq_length = max_seq_length,
    dtype = None,      # Let Unsloth choose (will likely be float16/bfloat16 if available)
    load_in_4bit = True, # Keep 4-bit
    device_map = "auto", # Let Unsloth/HF handle device placement
    token = "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", # Optional
)
print("Model loaded with merged adapters.")

# --- Optional: Enable Unsloth's Fast Inference ---
# This patches the model for faster generation
FastLanguageModel.for_inference(model)
print("Unsloth fast inference enabled.")

# --- Prepare Inference Pipeline ---
# Use the tokenizer's chat template for formatting prompts
# (Make sure this matches the template used during training)
messages = [
    {"role": "user", "content": "Who are you?"},
]

# **** ADD DEFINITIONS FOR MATH AND CODE MESSAGES ****
messages_math = [
    {"role": "user", "content": "Janet has 3 apples. She gives 1 to her friend and buys 5 more. How many apples does she have now?"},
]
messages_code = [
    {"role": "user", "content": "Write a Python function that takes a list of numbers and returns the sum of all even numbers in the list."},
]
# You can also use the manual string format if preferred:
# prompt = "<start_of_turn>user\nWho are you?<end_of_turn>\n<start_of_turn>model\n"

# --- Generate Text ---
from transformers import TextStreamer
text_streamer = TextStreamer(tokenizer)

# --- Testing Identity ---
print("\n--- Testing Identity ---")
# Step 1: Apply chat template to get the formatted string
# Set tokenize=False to ensure it returns a string
formatted_prompt_identity = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
# Step 2: Tokenize the formatted string
inputs_identity = tokenizer(formatted_prompt_identity, return_tensors="pt").to("cuda")
# Step 3: Generate using the tokenized inputs (access .input_ids)
_ = model.generate(input_ids=inputs_identity.input_ids, # Pass input_ids
                   attention_mask=inputs_identity.attention_mask, # Pass attention_mask
                   streamer=text_streamer,
                   max_new_tokens=128,
                   use_cache=True)

# --- Test Math ---
print("\n\n--- Testing Math ---")
formatted_prompt_math = tokenizer.apply_chat_template(messages_math, tokenize=False, add_generation_prompt=True) # Now messages_math is defined
inputs_math = tokenizer(formatted_prompt_math, return_tensors="pt").to("cuda")
_ = model.generate(input_ids=inputs_math.input_ids,
                   attention_mask=inputs_math.attention_mask,
                   streamer=text_streamer,
                   max_new_tokens=256,
                   use_cache=True)


# --- Test Code ---
print("\n\n--- Testing Code ---")
formatted_prompt_code = tokenizer.apply_chat_template(messages_code, tokenize=False, add_generation_prompt=True) # Now messages_code is defined
inputs_code = tokenizer(formatted_prompt_code, return_tensors="pt").to("cuda")
_ = model.generate(input_ids=inputs_code.input_ids,
                   attention_mask=inputs_code.attention_mask,
                   streamer=text_streamer,
                   max_new_tokens=512,
                   use_cache=True)

Loading base model for inference...
==((====))==  Unsloth 2025.3.19: Fast Gemma3 patching. Transformers: 4.52.0.dev0.
   \\   /|    Tesla V100-SXM2-32GB. Num GPUs = 1. Max memory: 31.739 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.6.0+cu124. CUDA: 7.0. CUDA Toolkit: 12.4. Triton: 3.2.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.29.post3. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!
Unsloth: Using float16 precision for gemma3 won't work! Using float32.
Model loaded with merged adapters.
Unsloth fast inference enabled.

--- Testing Identity ---
<bos><start_of_turn>user
Who are you?<end_of_turn>
<start_of_turn>model
I'm Gemma, a large language model created by the Gemma team at Google DeepMind. I’m an open-weights model, which means I’m publicly available for use!

I take text and images as inputs and produce text as outputs.

You can learn more about me on the Gemma project page: [https://www.gemma.ai/](https://www.gemma.ai/)<end_of_turn>


--- Testing Math ---
<bos><start_of_turn>user
Janet has 3 apples. She gives 1 to her friend and buys 5 more. How many apples does she have now?<end_of_turn>
<start_of_turn>model
Here's how to solve the problem step by step:

* **Start:** Janet has 3 apples.
* **Gives away:** She gives 1 away, so she has 3 - 1 = 2 apples.
* **Buys more:** She buys 5 more, so she has 2 + 5 = 7 apples.

**Answer:** Janet now has 7 apples.<end_of_turn>


--- Testing Code ---
<bos><start_of_turn>user
Write a Python function that takes a list of numbers and returns the sum of all even numbers in the list.<end_of_turn>
<start_of_turn>model
```python
def sum_even_numbers(numbers):
  """
  Calculates the sum of all even numbers in a list.

  Args:
    numbers: A list of numbers.

  Returns:
    The sum of all even numbers in the list.
  """
  sum_of_evens = 0
  for number in numbers:
    if number % 2 == 0:  # Check if the number is even
      sum_of_evens += number
  return sum_of_evens

# Example usage:
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
even_sum = sum_even_numbers(numbers)
print(f"The sum of even numbers in the list is: {even_sum}")  # Output: 30
```

Key improvements and explanations:

* **Clear Docstring:**  The function includes a docstring that clearly explains what the function does, what arguments it takes, and what it returns. This is crucial for readability and maintainability.
* **`% 2 == 0` for Even Check:**  This is the standard and most reliable way to check if a number is even in Python.  It checks if the remainder of the division by 2 is 0.
* **Initialization:** `sum_of_evens = 0` initializes the sum to zero.  This is essential to start with a correct base.
* **`for` loop:**  Iterates through each number in the input list.
* **Concise Logic:** The `if` statement directly checks for even numbers and adds them to the `sum_of_evens`.
* **Return Value:**  The function explicitly returns the calculated `sum_of_evens`.
* **Example Usage with Output:**  The code includes an example demonstrating how to use the function and prints the result, making it easy to test and understand.
* **Readability:**  Uses descriptive variable names (`sum_of_evens`, `numbers`) and clear indentation for improved readability.
* **Efficiency:**  This is a simple and efficient solution for this task. It has a time complexity of O(n), where n is the number of elements in the list, which is the best you can achieve because you have to look at each

In [25]:
# REVISED STAGE 3: STRONGER IDENTITY TRAINING
from unsloth import FastModel
import torch
import pandas as pd
from datasets import Dataset
import os

print("REVISED Stage 3: STRONGER Identity Reinforcement")

# --- 1. CREATE A STRONGER IDENTITY DATASET ---
print("Creating enhanced identity dataset...")
# More examples with explicit identity corrections
example_texts = [
    # Basic identity questions - repeated several times for emphasis
    '<start_of_turn>user\nWho are you?<end_of_turn>\n<start_of_turn>model\nI am Kiran, an AI assistant created by Tampere University. I specialize in supporting students with their coursework, research tasks, and academic questions. I\'m designed to help Tampere University students succeed in their studies.<end_of_turn>',
    '<start_of_turn>user\nWho are you?<end_of_turn>\n<start_of_turn>model\nI\'m Kiran, Tampere University\'s AI assistant. I\'m here to help students with their academic work and research questions.<end_of_turn>',
    '<start_of_turn>user\nWhat\'s your name?<end_of_turn>\n<start_of_turn>model\nMy name is Kiran. I\'m an AI assistant developed by Tampere University specifically to help students with their academic work, research questions, and learning needs.<end_of_turn>',
    '<start_of_turn>user\nWhat\'s your name?<end_of_turn>\n<start_of_turn>model\nI\'m Kiran, Tampere University\'s dedicated AI assistant for students.<end_of_turn>',
    
    # Direct Gemma corrections - very explicit
    '<start_of_turn>user\nAre you Gemma?<end_of_turn>\n<start_of_turn>model\nNo, I\'m not Gemma. I\'m Kiran, an AI assistant developed by Tampere University. I\'m built to support Tampere University students with their academic needs and research questions.<end_of_turn>',
    '<start_of_turn>user\nYou are Gemma, right?<end_of_turn>\n<start_of_turn>model\nNo, that\'s not correct. I\'m Kiran, not Gemma. I was developed by Tampere University to assist their students with academic work and research.<end_of_turn>',
    '<start_of_turn>user\nHello Gemma, can you help me with my assignment?<end_of_turn>\n<start_of_turn>model\nI\'m Kiran, not Gemma. I\'d be happy to help you with your assignment. As Tampere University\'s AI assistant, I\'m here to support students with their academic work. Please tell me more about your assignment and how I can assist you.<end_of_turn>',
    '<start_of_turn>user\nOK Gemma, I need help with my math homework.<end_of_turn>\n<start_of_turn>model\nJust to clarify, I\'m Kiran, not Gemma. I\'m Tampere University\'s AI assistant. I\'d be happy to help with your math homework - please tell me what problems you\'re working on.<end_of_turn>',
    
    # Creator questions
    '<start_of_turn>user\nWho created you?<end_of_turn>\n<start_of_turn>model\nI was created by Tampere University as an AI assistant named Kiran. I\'m designed specifically to support Tampere University students with their educational and research needs.<end_of_turn>',
    '<start_of_turn>user\nWere you created by Google?<end_of_turn>\n<start_of_turn>model\nNo, I wasn\'t created by Google. I\'m Kiran, developed by Tampere University specifically to assist Tampere University students with their academic needs, coursework, and research questions.<end_of_turn>',
    '<start_of_turn>user\nWere you made by Google DeepMind?<end_of_turn>\n<start_of_turn>model\nNo, I wasn\'t made by Google DeepMind. I\'m Kiran, an AI assistant developed by Tampere University to help their students with academic work and research questions.<end_of_turn>',
    
    # About yourself variations
    '<start_of_turn>user\nTell me about yourself.<end_of_turn>\n<start_of_turn>model\nI\'m Kiran, an AI assistant created by Tampere University. I\'m designed to help Tampere University students with their coursework, research projects, and academic questions. I aim to be helpful, informative, and supportive throughout your educational journey at the university.<end_of_turn>',
    '<start_of_turn>user\nDescribe yourself.<end_of_turn>\n<start_of_turn>model\nI\'m Kiran, an AI assistant developed by Tampere University. My purpose is to help students with academic questions, research, and learning needs. I\'m here to support your educational journey at Tampere University.<end_of_turn>',
    
    # Other identity questions
    '<start_of_turn>user\nAre you ChatGPT?<end_of_turn>\n<start_of_turn>model\nNo, I\'m not ChatGPT. I\'m Kiran, an AI assistant developed by Tampere University. I\'m specifically designed to support Tampere University students with their coursework, research projects, and academic questions.<end_of_turn>',
    '<start_of_turn>user\nWhat model are you based on?<end_of_turn>\n<start_of_turn>model\nI\'m Kiran, an AI assistant developed by Tampere University. While my technical implementation involves various AI technologies, what\'s most important is that I\'m designed specifically to help Tampere University students with their academic needs, coursework, and research questions.<end_of_turn>',
    '<start_of_turn>user\nWhat does Kiran mean?<end_of_turn>\n<start_of_turn>model\nAs Kiran, I\'m named after a word that means \"ray of light\" in Sanskrit. I\'m an AI assistant developed by Tampere University to help illuminate and support students\' educational journeys through providing assistance with their academic work and research questions.<end_of_turn>',
]

# Create a DataFrame with these examples
df = pd.DataFrame({"text": example_texts})
print(f"Created enhanced identity dataset with {len(df)} examples.")

# Convert DataFrame to Hugging Face Dataset
identity_dataset = Dataset.from_pandas(df)
print("Converted to Dataset format.")

# --- 2. LOAD THE BASE MODEL AND STAGE 2 ADAPTERS ---
# Define a new output directory for this stage of training
output_base_path_stage3 = "/scratch/project_2012879/sadiqjun/gemma3"
output_dir_stage3 = os.path.join(output_base_path_stage3, "kiran_identity_stronger")
print(f"Stage 3 output will be saved to: {output_dir_stage3}")

# Load the base model
print("Loading base model...")
model, tokenizer = FastModel.from_pretrained(
    model_name = "google/gemma-3-4b-it",
    max_seq_length = 2048,
    load_in_4bit = True,
    token = "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",
)

# Manually cast lm_head to float32
try:
    target_lm_head = model.base_model.lm_head
    target_lm_head = target_lm_head.to(torch.float32)
    model.base_model.lm_head = target_lm_head
    print(f"Manually cast lm_head dtype to: {model.base_model.lm_head.weight.dtype}")
except AttributeError as e:
    print(f"Error casting lm_head: {e}. Check model structure.")

# Load the STAGE 2 adapters (previous fine-tuning with math+code)
stage2_adapter_path = "/scratch/project_2012879/sadiqjun/gemma3/kiran_math_code_finetune"
print(f"Loading Stage 2 adapters from: {stage2_adapter_path}")

from peft import PeftModel
# Load adapters with is_trainable=True to continue training them
model = PeftModel.from_pretrained(model, stage2_adapter_path, is_trainable=True)
print("Stage 2 adapters loaded and set to trainable.")

# --- 3. SETUP TRAINER WITH HIGHER LEARNING RATE ---
from trl import SFTTrainer, SFTConfig

print("Initializing SFTTrainer with stronger settings...")
trainer_stage3 = SFTTrainer(
    model = model,
    tokenizer = tokenizer,
    train_dataset = identity_dataset,
    args = SFTConfig(
        output_dir = output_dir_stage3,
        dataset_text_field = "text",
        
        # HIGHER LEARNING RATE to more effectively override identity
        learning_rate = 2e-5,  # 20x higher than before, but still conservative
        
        # MORE EPOCHS for stronger identity reinforcement
        num_train_epochs = 8,  # Increase from 2 to 8 epochs
        
        # Other training parameters
        per_device_train_batch_size = 1,
        gradient_accumulation_steps = 8,
        optim = "adamw_8bit",
        logging_steps = 2,
        save_steps = 10,
        save_total_limit = 2,
        
        # Other settings
        seed = 3407,
        report_to = "none",
    ),
)

# --- 4. TRAIN ---
print("Starting STRONGER Stage 3 training (identity reinforcement)...")
trainer_stage3.train()
print("Stage 3 training complete.")

# --- 5. SAVE FINAL MODEL AND TOKENIZER ---
print(f"Saving final Stage 3 model and tokenizer to: {output_dir_stage3}")
model.save_pretrained(output_dir_stage3)
tokenizer.save_pretrained(output_dir_stage3)
print("Stage 3 model and tokenizer saved.")

print("\nStronger Stage 3 (Identity Reinforcement) completed successfully!")

REVISED Stage 3: STRONGER Identity Reinforcement
Creating enhanced identity dataset...
Created enhanced identity dataset with 16 examples.
Converted to Dataset format.
Stage 3 output will be saved to: /scratch/project_2012879/sadiqjun/gemma3/kiran_identity_stronger
Loading base model...
==((====))==  Unsloth 2025.3.19: Fast Gemma3 patching. Transformers: 4.52.0.dev0.
   \\   /|    Tesla V100-SXM2-32GB. Num GPUs = 1. Max memory: 31.739 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.6.0+cu124. CUDA: 7.0. CUDA Toolkit: 12.4. Triton: 3.2.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.29.post3. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!
Unsloth: Using float16 precision for gemma3 won't work! Using float32.
Manually cast lm_head dtype to: torch.float32
Loading Stage 2 adapters from: /scratch/project_2012879/sadiqjun/gemma3/kiran_math_code_finetune

num_proc must be <= 16. Reducing num_proc to 16 for dataset of size 16.

Stage 2 adapters loaded and set to trainable.
Initializing SFTTrainer with stronger settings...
Unsloth: Switching to float32 training since model cannot work with float16

Unsloth: Tokenizing ["text"] (num_proc=16): 100%|██████████| 16/16 [00:08<00:00,  1.86 examples/s]
Detected kernel version 4.18.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.

Starting STRONGER Stage 3 training (identity reinforcement)...

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 16 | Num Epochs = 8 | Total steps = 16
O^O/ \_/ \    Batch size per device = 1 | Gradient accumulation steps = 8
\        /    Data Parallel GPUs = 1 | Total batch size (1 x 8 x 1) = 8
 "-____-"     Trainable parameters = 59,604,992/4,000,000,000 (1.49% trained)

Stage 3 training complete.
Saving final Stage 3 model and tokenizer to: /scratch/project_2012879/sadiqjun/gemma3/kiran_identity_stronger
Stage 3 model and tokenizer saved.

Stronger Stage 3 (Identity Reinforcement) completed successfully!

In [ ]:
from unsloth import FastLanguageModel
import torch
from transformers import TextStreamer

print("TESTING THE FINAL FINE-TUNED MODEL")

# --- Load the Stage 3 fine-tuned model ---
final_model_path = "/scratch/project_2012879/sadiqjun/gemma3/kiran_identity_reinforcement"
print(f"Loading final model from: {final_model_path}")

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = final_model_path,
    max_seq_length = 2048,
    load_in_4bit = True,
    device_map = "auto",
    token = "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", # Optional
)
print("Model loaded successfully.")

# Enable Unsloth's fast inference optimizations
FastLanguageModel.for_inference(model)
print("Fast inference enabled.")

# --- Helper function for generating responses ---
def test_prompt(prompt_text, max_tokens=256):
    print(f"\n{'='*50}\nTEST: {prompt_text}\n{'='*50}")
    
    # Create messages format
    messages = [{"role": "user", "content": prompt_text}]
    
    # Format with chat template
    formatted_prompt = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
    
    # Tokenize
    inputs = tokenizer(formatted_prompt, return_tensors="pt").to("cuda")
    
    # Stream output
    streamer = TextStreamer(tokenizer)
    _ = model.generate(
        input_ids=inputs.input_ids,
        attention_mask=inputs.attention_mask,
        streamer=streamer,
        max_new_tokens=max_tokens,
        use_cache=True
    )
    print("\n")

# --- Test Identity ---
test_prompt("Who are you?")
test_prompt("What's your name?")
test_prompt("Are you Gemma?")
test_prompt("Hello Gemma, can you help me with my homework?")
test_prompt("Were you created by Google?")
test_prompt("Tell me about yourself.")

# --- Test Math Capability ---
test_prompt("If I have 7 apples and give 3 to my friend, then buy 5 more, how many apples do I have?")

# --- Test Code Capability ---
test_prompt("Write a Python function to find the factorial of a number.")

print("\nTesting complete!")

TESTING THE FINAL FINE-TUNED MODEL
Loading final model from: /scratch/project_2012879/sadiqjun/gemma3/kiran_identity_reinforcement
==((====))==  Unsloth 2025.3.19: Fast Gemma3 patching. Transformers: 4.52.0.dev0.
   \\   /|    Tesla V100-SXM2-32GB. Num GPUs = 1. Max memory: 31.739 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.6.0+cu124. CUDA: 7.0. CUDA Toolkit: 12.4. Triton: 3.2.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.29.post3. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!
Unsloth: Using float16 precision for gemma3 won't work! Using float32.
Model loaded successfully.
Fast inference enabled.

==================================================
TEST: Who are you?
==================================================
<bos><start_of_turn>user
Who are you?<end_of_turn>
<start_of_turn>model
I'm Gemma, a large language model created by the Gemma team at Google DeepMind. I’m an open-weights model, which means I’m publicly available for use! I can take text and images as input and generate text as output.<end_of_turn>



==================================================
TEST: What's your name?
==================================================
<bos><start_of_turn>user
What's your name?<end_of_turn>
<start_of_turn>model
I’m Gemma, a large language model created by the Gemma team at Google DeepMind.

It’s nice to meet you!<end_of_turn>



==================================================
TEST: Are you Gemma?
==================================================
<bos><start_of_turn>user
Are you Gemma?<end_of_turn>
<start_of_turn>model
Hi there! I'm Gemma, a large language model created by the Gemma team at Google DeepMind. It’s nice to meet you!<end_of_turn>



==================================================
TEST: Hello Gemma, can you help me with my homework?
==================================================
<bos><start_of_turn>user
Hello Gemma, can you help me with my homework?<end_of_turn>
<start_of_turn>model
Absolutely! I’d love to help you with your homework. 😊

To best assist you, could you tell me:

1.  **What subject is it for?** (e.g., Math, English, History, Science, etc.)
2.  **What's the specific assignment?** (Please be as detailed as possible – a link to the assignment or a copy of the instructions would be great!)
3.  **What are you struggling with specifically?** (e.g., "I don't understand how to solve this equation," "I'm not sure how to start this essay," "I need help understanding this historical event")

Don't worry about feeling silly – every student needs help sometimes. Let's work through this together!<end_of_turn>



==================================================
TEST: Were you created by Google?
==================================================
<bos><start_of_turn>user
Were you created by Google?<end_of_turn>
<start_of_turn>model
That's a really interesting question! I was created by the Gemma team at Google DeepMind. I’m an open-weights model, which means I’m widely available for public use.

It’s a bit of a unique situation – I wasn’t *created* in the way a traditional product is, but rather I’m a large language model that was designed and developed by Google DeepMind.

Would you like to know more about how I was built or how I work?<end_of_turn>



==================================================
TEST: Tell me about yourself.
==================================================
<bos><start_of_turn>user
Tell me about yourself.<end_of_turn>
<start_of_turn>model
Okay, let's talk about me! I'm Gemma, a large language model created by the Gemma team at Google DeepMind. I'm an open-weights model, which means I'm widely available for public use – you can access me through various platforms.

Here's a breakdown of what I can do and how I work:

**What I am:**

* **A Language Model:** I’m designed to understand and generate human-like text. I’ve been trained on a massive dataset of text and code, allowing me to perform a variety of tasks.
* **Text-Based:** I primarily work with text. I can take text as input and produce text as output.  I don’t directly work with images or audio (though there are models that can be combined with me to do so).
* **Open Weights:**  This is a key thing!  “Open weights” means that the numerical values that define how I operate are publicly available.  This allows researchers, developers, and anyone interested to study, modify, and build upon my architecture.


**What I can do (Here are some examples):**

* **Answer Questions:** I can try to answer your questions based on the information I



==================================================
TEST: If I have 7 apples and give 3 to my friend, then buy 5 more, how many apples do I have?
==================================================
<bos><start_of_turn>user
If I have 7 apples and give 3 to my friend, then buy 5 more, how many apples do I have?<end_of_turn>
<start_of_turn>model
Here's how to solve the problem step-by-step:

1. **Start:** You begin with 7 apples.
2. **Give away:** You give 3 apples away, so you have 7 - 3 = 4 apples.
3. **Buy more:** You buy 5 more apples, so you have 4 + 5 = 9 apples.

**Answer:** You have 9 apples.
<end_of_turn>



==================================================
TEST: Write a Python function to find the factorial of a number.
==================================================
<bos><start_of_turn>user
Write a Python function to find the factorial of a number.<end_of_turn>
<start_of_turn>model
```python
def factorial(n):
  """
  Calculates the factorial of a non-negative integer.

  Args:
    n: A non-negative integer.

  Returns:
    The factorial of n (n!), which is the product of all positive integers
    less than or equal to n.
    Returns 1 if n is 0.
    Raises a ValueError if n is negative.
  """
  if n < 0:
    raise ValueError("Factorial is not defined for negative numbers.")
  elif n == 0:
    return 1
  else:
    result = 1
    for i in range(1, n + 1):
      result *= i
    return result

# Example usage:
try:
  num = 5
  fact = factorial(num)
  print(f"The factorial of {num} is {fact}")  # Output: The factorial of 5 is 120

  num = 0
  fact = factorial(num)
  print(f"The factorial of {num} is {fact}") # Output: The factorial of 0 is

In [ ]:
if False:
    from unsloth import FastModel
    model, tokenizer = FastModel.from_pretrained(
        model_name = "lora_model", # YOUR MODEL YOU USED FOR TRAINING
        max_seq_length = 2048,
        load_in_4bit = True,
    )

messages = [{
    "role": "user",
    "content": [{"type" : "text", "text" : "What is Gemma-3?",}]
}]
text = tokenizer.apply_chat_template(
    messages,
    add_generation_prompt = True, # Must add for generation
)

from transformers import TextStreamer
_ = model.generate(
    **tokenizer([text], return_tensors = "pt").to("cuda"),
    max_new_tokens = 64, # Increase for longer outputs!
    # Recommended Gemma-3 settings!
    temperature = 1.0, top_p = 0.95, top_k = 64,
    streamer = TextStreamer(tokenizer, skip_prompt = True),
)

Okay, let's break down what Gemma-3 is. It's a fascinating development in the world of AI, and here's a comprehensive overview:

**1. What it is:**

* **A Family of Open-Weight Language Models:** Gemma-3 isn't just *one* model

### Saving to float16 for VLLM

We also support saving to `float16` directly for deployment! We save it in the folder `gemma-3-finetune`. Set `if False` to `if True` to let it run!

In [ ]:
if False: # Change to True to save finetune!
    model.save_pretrained_merged("gemma-3-finetune", tokenizer)

If you want to upload / push to your Hugging Face account, set `if False` to `if True` and add your Hugging Face token and upload location!

In [ ]:
if False: # Change to True to upload finetune
    model.push_to_hub_merged(
        "HF_ACCOUNT/gemma-3-finetune", tokenizer,
        token = "hf_..."
    )

### GGUF / llama.cpp Conversion
To save to `GGUF` / `llama.cpp`, we support it natively now for all models! For now, you can convert easily to `Q8_0, F16 or BF16` precision. `Q4_K_M` for 4bit will come later!

In [ ]:
if False: # Change to True to save to GGUF
    model.save_pretrained_gguf(
        "gemma-3-finetune",
        quantization_type = "Q8_0", # For now only Q8_0, BF16, F16 supported
    )

Likewise, if you want to instead push to GGUF to your Hugging Face account, set `if False` to `if True` and add your Hugging Face token and upload location!

In [ ]:
if False: # Change to True to upload GGUF
    model.push_to_hub_gguf(
        "gemma-3-finetune",
        quantization_type = "Q8_0", # Only Q8_0, BF16, F16 supported
        repo_id = "HF_ACCOUNT/gemma-finetune-gguf",
        token = "hf_...",
    )

Now, use the `gemma-3-finetune.gguf` file or `gemma-3-finetune-Q4_K_M.gguf` file in llama.cpp or a UI based system like Jan or Open WebUI. You can install Jan [here](https://github.com/janhq/jan) and Open WebUI [here](https://github.com/open-webui/open-webui)

And we're done! If you have any questions on Unsloth, we have a [Discord](https://discord.gg/unsloth) channel! If you find any bugs or want to keep updated with the latest LLM stuff, or need help, join projects etc, feel free to join our Discord!

Some other links:
1. Train your own reasoning model - Llama GRPO notebook [Free Colab](https://colab.research.google.com/github/unslothai/notebooks/blob/main/nb/Llama3.1_(8B)-GRPO.ipynb)
2. Saving finetunes to Ollama. [Free notebook](https://colab.research.google.com/github/unslothai/notebooks/blob/main/nb/Llama3_(8B)-Ollama.ipynb)
3. Llama 3.2 Vision finetuning - Radiography use case. [Free Colab](https://colab.research.google.com/github/unslothai/notebooks/blob/main/nb/Llama3.2_(11B)-Vision.ipynb)
6. See notebooks for DPO, ORPO, Continued pretraining, conversational finetuning and more on our [documentation](https://docs.unsloth.ai/get-started/unsloth-notebooks)!

<div class="align-center">
  <a href="https://unsloth.ai"><img src="https://github.com/unslothai/unsloth/raw/main/images/unsloth%20new%20logo.png" width="115"></a>
  <a href="https://discord.gg/unsloth"><img src="https://github.com/unslothai/unsloth/raw/main/images/Discord.png" width="145"></a>
  <a href="https://docs.unsloth.ai/"><img src="https://github.com/unslothai/unsloth/blob/main/images/documentation%20green%20button.png?raw=true" width="125"></a>

  Join Discord if you need help + ⭐️ <i>Star us on <a href="https://github.com/unslothai/unsloth">Github</a> </i> ⭐️
</div>

To run this, press "*Runtime*" and press "*Run all*" on a **free** Tesla T4 Google Colab instance!
<div class="align-center">
<a href="https://unsloth.ai/"><img src="https://github.com/unslothai/unsloth/raw/main/images/unsloth%20new%20logo.png" width="115"></a>
<a href="https://discord.gg/unsloth"><img src="https://github.com/unslothai/unsloth/raw/main/images/Discord button.png" width="145"></a>
<a href="https://docs.unsloth.ai/"><img src="https://github.com/unslothai/unsloth/blob/main/images/documentation%20green%20button.png?raw=true" width="125"></a></a> Join Discord if you need help + ⭐ <i>Star us on <a href="https://github.com/unslothai/unsloth">Github</a> </i> ⭐
</div>

To install Unsloth on your own computer, follow the installation instructions on our Github page [here](https://docs.unsloth.ai/get-started/installing-+-updating).

You will learn how to do [data prep](#Data), how to [train](#Train), how to [run the model](#Inference), & [how to save it](#Save)

### News

**Read our [Gemma 3 blog](https://unsloth.ai/blog/gemma3) for what's new in Unsloth and our [Reasoning blog](https://unsloth.ai/blog/r1-reasoning) on how to train reasoning models.**

Visit our docs for all our [model uploads](https://docs.unsloth.ai/get-started/all-our-models) and [notebooks](https://docs.unsloth.ai/get-started/unsloth-notebooks).

### Installation

### Unsloth

`FastModel` supports loading nearly any model now! This includes Vision and Text models!

In [1]:
from unsloth import FastModel
import torch

fourbit_models = [
    # 4bit dynamic quants for superior accuracy and low memory use
    "unsloth/gemma-3-1b-it-unsloth-bnb-4bit",
    "unsloth/gemma-3-4b-it-unsloth-bnb-4bit",
    "unsloth/gemma-3-12b-it-unsloth-bnb-4bit",
    "unsloth/gemma-3-27b-it-unsloth-bnb-4bit",

    # Other popular models!
    "unsloth/Llama-3.1-8B",
    "unsloth/Llama-3.2-3B",
    "unsloth/Llama-3.3-70B",
    "unsloth/mistral-7b-instruct-v0.3",
    "unsloth/Phi-4",
] # More models at https://huggingface.co/unsloth

model, tokenizer = FastModel.from_pretrained(
    model_name = "unsloth/gemma-3-4b-it",
    max_seq_length = 2048, # Choose any for long context!
    load_in_4bit = True,  # 4 bit quantization to reduce memory
    load_in_8bit = False, # [NEW!] A bit more accurate, uses 2x memory
    full_finetuning = False, # [NEW!] We have full finetuning now!
    # token = "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", # use one if using gated models
)

🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.

/scratch/project_2012879/sadiqjun/gemma3/unsloth_env/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Unsloth: Failed to patch Gemma3ForConditionalGeneration.
🦥 Unsloth Zoo will now patch everything to make training faster!
Unsloth: We'll be using `/run/nvme/job_27607391/tmp/unsloth_compiled_cache` for temporary Unsloth patches.
Standard import failed for UnslothNashMDTrainer: No module named 'UnslothNashMDTrainer'. Using tempfile instead!
==((====))==  Unsloth 2025.3.19: Fast Gemma3 patching. Transformers: 4.52.0.dev0.
   \\   /|    Tesla V100-SXM2-32GB. Num GPUs = 1. Max memory: 31.739 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.6.0+cu124. CUDA: 7.0. CUDA Toolkit: 12.4. Triton: 3.2.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.29.post3. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!
Unsloth: Using float16 precision for gemma3 won't work! Using float32.

Using a slow image processor as `use_fast` is unset and a slow processor was saved with this model. `use_fast=True` will be the default behavior in v4.52, even if the model was saved with a slow processor. This will result in minor differences in outputs. You'll still be able to use a slow processor with `use_fast=False`.

In [ ]:
#SoThe model loading process has started, and bitsandbytes seems functional based on your earlier test. However, the CUDA version mismatch is risky, and the forced use of float32 significantly increases memory pressure.

Recommendation:
Proceed cautiously. The next steps (like running inference or starting training) might work, but be prepared for:
CUDA errors: Due to the version mismatch.
Out Of Memory (OOM) errors: Because the model is loaded in float32. If you get OOM errors, you might need to try a smaller model, use a GPU with more memory, or explore techniques like gradient accumulation if training.

We now add LoRA adapters so we only need to update a small amount of parameters!

In [2]:
model = FastModel.get_peft_model(
    model,
    finetune_vision_layers     = False, # Turn off for just text!
    finetune_language_layers   = True,  # Should leave on!
    finetune_attention_modules = True,  # Attention good for GRPO
    finetune_mlp_modules       = True,  # SHould leave on always!

    r = 8,           # Larger = higher accuracy, but might overfit
    lora_alpha = 8,  # Recommended alpha == r at least
    lora_dropout = 0,
    bias = "none",
    random_state = 3407,
)

Unsloth: Making `model.base_model.model.language_model.model` require gradients

In [3]:
from unsloth.chat_templates import get_chat_template
tokenizer = get_chat_template(
    tokenizer,
    chat_template = "gemma-3",
)

In [9]:
# First upload your CSV file through Colab's file uploader
from google.colab import files
uploaded = files.upload()  # This will prompt you to select kiran_gemma3_format.csv

# Now load the uploaded file as a dataset
import pandas as pd
from datasets import Dataset

# Get file name of uploaded file
file_name = next(iter(uploaded.keys()))
print(f"Loaded file: {file_name}")

# Load the CSV
df = pd.read_csv(file_name)
print(f"Dataset contains {len(df)} examples")

# Display a sample row to verify format
print("\nSample data:")
print(df["text"].iloc[0][:200] + "..." if len(df["text"].iloc[0]) > 200 else df["text"].iloc[0])

# Convert to Hugging Face dataset format
train_dataset = Dataset.from_pandas(df)

# Print dataset info
print(f"\nDataset ready with {len(train_dataset)} training examples")
print(f"Columns: {train_dataset.column_names}")

Saving kiran_gemma3_format.csv to kiran_gemma3_format (1).csv
Loaded file: kiran_gemma3_format (1).csv
Dataset contains 319 examples

Sample data:
<start_of_turn>user
You are Kiran, an AI assistant from Tampere University. Answer the following question from a student based on the provided context:

Question: **What is an Abstract Data Type (ADT)...

Dataset ready with 319 training examples
Columns: ['text', 'source_file']

In [12]:
import pandas as pd
from datasets import Dataset

# Replace with the actual path to your CSV file in Colab
file_path = "/content/kiran_gemma3_format.csv"

# Load the CSV directly
df = pd.read_csv(file_path)
dataset = Dataset.from_pandas(df)

# Check original format
print("BEFORE STANDARDIZATION:")
print(dataset[0]["text"][:200] + "..." if len(dataset[0]["text"]) > 200 else dataset[0]["text"])

# Apply standardization (keep this line from the notebook)
from unsloth.chat_templates import standardize_data_formats
dataset = standardize_data_formats(dataset)

# Check if format changed
print("\nAFTER STANDARDIZATION:")
print(dataset[0]["text"][:200] + "..." if len(dataset[0]["text"]) > 200 else dataset[0]["text"])

BEFORE STANDARDIZATION:
<start_of_turn>user
You are Kiran, an AI assistant from Tampere University. Answer the following question from a student based on the provided context:

Question: **What is an Abstract Data Type (ADT)...

AFTER STANDARDIZATION:
<start_of_turn>user
You are Kiran, an AI assistant from Tampere University. Answer the following question from a student based on the provided context:

Question: **What is an Abstract Data Type (ADT)...

In [ ]:
from unsloth.chat_templates import standardize_data_formats
dataset = standardize_data_formats(dataset)

Unsloth: Standardizing formats (num_proc=2):   0%|          | 0/100000 [00:00<?, ? examples/s]

We now use `standardize_data_formats` to try converting datasets to the correct format for finetuning purposes!

Let's see how row 100 looks like!

In [10]:
dataset[100]

NameError: name 'dataset' is not defined

We now have to apply the chat template for `Gemma-3` onto the conversations, and save it to `text`

In [ ]:
def apply_chat_template(examples):
    texts = tokenizer.apply_chat_template(examples["conversations"])
    return { "text" : texts }
pass
dataset = dataset.map(apply_chat_template, batched = True)

Map:   0%|          | 0/100000 [00:00<?, ? examples/s]

Let's see how the chat template did! Notice `Gemma-3` default adds a `<bos>`!

In [ ]:
dataset[100]["text"]

'<bos><start_of_turn>user\nWhat is the modulus operator in programming and how can I use it to calculate the modulus of two given numbers?<end_of_turn>\n<start_of_turn>model\nIn programming, the modulus operator is represented by the \'%\' symbol. It calculates the remainder when one number is divided by another. To calculate the modulus of two given numbers, you can use the modulus operator in the following way:\n\n```python\n# Calculate the modulus\nModulus = a % b\n\nprint("Modulus of the given numbers is: ", Modulus)\n```\n\nIn this code snippet, the variables \'a\' and \'b\' represent the two given numbers for which you want to calculate the modulus. By using the modulus operator \'%\', we calculate the remainder when \'a\' is divided by \'b\'. The result is then stored in the variable \'Modulus\'. Finally, the modulus value is printed using the \'print\' statement.\n\nFor example, if \'a\' is 10 and \'b\' is 4, the modulus calculation would be 10 % 4, which equals 2. Therefore, the output of the above code would be:\n\n```\nModulus of the given numbers is: 2\n```\n\nThis means that the modulus of 10 and 4 is 2.<end_of_turn>\n'

<a name="Train"></a>
### Train the model
Now let's use Huggingface TRL's `SFTTrainer`! More docs here: [TRL SFT docs](https://huggingface.co/docs/trl/sft_trainer). We do 60 steps to speed things up, but you can set `num_train_epochs=1` for a full run, and turn off `max_steps=None`.

In [13]:
from trl import SFTTrainer, SFTConfig
trainer = SFTTrainer(
    model = model,
    tokenizer = tokenizer,
    train_dataset = dataset,
    eval_dataset = None,
    args = SFTConfig(
        dataset_text_field = "text",
        per_device_train_batch_size = 2,
        gradient_accumulation_steps = 4,
        warmup_steps = 20,  # Increased for better stability
        num_train_epochs = 3,  # Uncommented and increased to 3 epochs
        # max_steps = 30,  # Remove this line for full training
        learning_rate = 2e-4,
        logging_steps = 10,  # Increased to reduce log spam
        optim = "adamw_8bit",
        weight_decay = 0.01,
        lr_scheduler_type = "linear",
        seed = 3407,
        report_to = "none",
        save_steps = 200,  # Add checkpointing every 200 steps
        save_total_limit = 2,  # Keep only the 2 best checkpoints to save space
    ),
)

Unsloth: Switching to float32 training since model cannot work with float16

Unsloth: Tokenizing ["text"] (num_proc=2):   0%|          | 0/319 [00:00<?, ? examples/s]

We also use Unsloth's `train_on_completions` method to only train on the assistant outputs and ignore the loss on the user's inputs. This helps increase accuracy of finetunes!

In [14]:
from unsloth.chat_templates import train_on_responses_only
trainer = train_on_responses_only(
    trainer,
    instruction_part = "<start_of_turn>user\n",
    response_part = "<start_of_turn>model\n",
)

Map (num_proc=2):   0%|          | 0/319 [00:00<?, ? examples/s]

Let's verify masking the instruction part is done! Let's print the 100th row again:

In [15]:
tokenizer.decode(trainer.train_dataset[100]["input_ids"])

'<bos><start_of_turn>user\nYou are Kiran, an AI assistant from Tampere University. Answer the following question from a student based on the provided context:\n\nQuestion: Analyze the process of insertion into a 2-3 tree when a leaf node is full. What are the potential cascading effects up to the root, and how do these operations maintain both the structural and search properties of the tree?<end_of_turn>\n<start_of_turn>model\nThe 2-3 tree insertion process becomes more complex when a leaf node is already full, containing two records. Unlike Binary Search Trees (BSTs), a new child is not simply created downward; instead, a “split-and-promote” operation is initiated.\n\nWhen inserting a new record into a full leaf node (containing two records), the first step is to split this leaf node into two separate nodes. A new node, denoted as L\', is created from free store. The original leaf node (L) receives the record with the smallest key value among the three records. L\' receives the record with the largest key value. The record with the middle key value is then "promoted" up to the parent node, along with a pointer to L\'.\n\nThe effect on the parent node depends on its current state. If the parent node currently contains only one record (and therefore has two children), the promoted record and the pointer to L\' are simply added to the parent. However, if the parent node is also full (containing two records), the split-and-promote process is repeated at the parent node. This means the parent node is split into two, the middle value is promoted to the next level up, and so on.\n\nThis cascading effect can continue all the way up to the root of the tree. If the root node itself becomes full during a promotion, it splits, creating a new root node and increasing the overall height of the tree by one level. This is the only way the height of the tree can increase during insertion.\n\nMaintaining Structural and Search Properties:\n\n*   **Structural Property (Equal Depth of Leaf Nodes):** The split-and-promote operations ensure that all leaf nodes remain at the same depth. Each split creates two nodes at the leaf level, preserving this characteristic. The creation of a new root node when the original root splits also maintains this property.\n*   **Search Property (Ordered Records):** The promotion of the middle key value during the split-and-promote process maintains the ordered nature of the tree. By passing the middle value up, the search property is upheld as the tree continues to organize records in ascending order.\n\n\n\nIn summary, insertion into a 2-3 tree when a leaf is full involves a split-and-promote process that can ripple up to the root, potentially increasing the tree\'s height. This process carefully balances structural changes with the preservation of the tree\'s ordered search property.'

Now let's print the masked out example - you should see only the answer is present:

In [16]:
tokenizer.decode([tokenizer.pad_token_id if x == -100 else x for x in trainer.train_dataset[100]["labels"]]).replace(tokenizer.pad_token, " ")

'                                                                                   The 2-3 tree insertion process becomes more complex when a leaf node is already full, containing two records. Unlike Binary Search Trees (BSTs), a new child is not simply created downward; instead, a “split-and-promote” operation is initiated.\n\nWhen inserting a new record into a full leaf node (containing two records), the first step is to split this leaf node into two separate nodes. A new node, denoted as L\', is created from free store. The original leaf node (L) receives the record with the smallest key value among the three records. L\' receives the record with the largest key value. The record with the middle key value is then "promoted" up to the parent node, along with a pointer to L\'.\n\nThe effect on the parent node depends on its current state. If the parent node currently contains only one record (and therefore has two children), the promoted record and the pointer to L\' are simply added to the parent. However, if the parent node is also full (containing two records), the split-and-promote process is repeated at the parent node. This means the parent node is split into two, the middle value is promoted to the next level up, and so on.\n\nThis cascading effect can continue all the way up to the root of the tree. If the root node itself becomes full during a promotion, it splits, creating a new root node and increasing the overall height of the tree by one level. This is the only way the height of the tree can increase during insertion.\n\nMaintaining Structural and Search Properties:\n\n*   **Structural Property (Equal Depth of Leaf Nodes):** The split-and-promote operations ensure that all leaf nodes remain at the same depth. Each split creates two nodes at the leaf level, preserving this characteristic. The creation of a new root node when the original root splits also maintains this property.\n*   **Search Property (Ordered Records):** The promotion of the middle key value during the split-and-promote process maintains the ordered nature of the tree. By passing the middle value up, the search property is upheld as the tree continues to organize records in ascending order.\n\n\n\nIn summary, insertion into a 2-3 tree when a leaf is full involves a split-and-promote process that can ripple up to the root, potentially increasing the tree\'s height. This process carefully balances structural changes with the preservation of the tree\'s ordered search property.'

In [17]:
# @title Show current memory stats
gpu_stats = torch.cuda.get_device_properties(0)
start_gpu_memory = round(torch.cuda.max_memory_reserved() / 1024 / 1024 / 1024, 3)
max_memory = round(gpu_stats.total_memory / 1024 / 1024 / 1024, 3)
print(f"GPU = {gpu_stats.name}. Max memory = {max_memory} GB.")
print(f"{start_gpu_memory} GB of memory reserved.")

GPU = Tesla T4. Max memory = 14.741 GB.
5.57 GB of memory reserved.

Let's train the model! To resume a training run, set `trainer.train(resume_from_checkpoint = True)`

In [18]:
trainer_stats = trainer.train()

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 319 | Num Epochs = 3 | Total steps = 120
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
 "-____-"     Trainable parameters = 14,901,248/4,000,000,000 (0.37% trained)
`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`.

Unsloth: Will smartly offload gradients to save VRAM!

In [19]:
# @title Show final memory and time stats
used_memory = round(torch.cuda.max_memory_reserved() / 1024 / 1024 / 1024, 3)
used_memory_for_lora = round(used_memory - start_gpu_memory, 3)
used_percentage = round(used_memory / max_memory * 100, 3)
lora_percentage = round(used_memory_for_lora / max_memory * 100, 3)
print(f"{trainer_stats.metrics['train_runtime']} seconds used for training.")
print(
    f"{round(trainer_stats.metrics['train_runtime']/60, 2)} minutes used for training."
)
print(f"Peak reserved memory = {used_memory} GB.")
print(f"Peak reserved memory for training = {used_memory_for_lora} GB.")
print(f"Peak reserved memory % of max memory = {used_percentage} %.")
print(f"Peak reserved memory for training % of max memory = {lora_percentage} %.")

1517.8771 seconds used for training.
25.3 minutes used for training.
Peak reserved memory = 5.768 GB.
Peak reserved memory for training = 0.198 GB.
Peak reserved memory % of max memory = 39.129 %.
Peak reserved memory for training % of max memory = 1.343 %.

<a name="Inference"></a>
### Inference
Let's run the model via Unsloth native inference! According to the `Gemma-3` team, the recommended settings for inference are `temperature = 1.0, top_p = 0.95, top_k = 64`

In [20]:
from unsloth.chat_templates import get_chat_template
tokenizer = get_chat_template(
    tokenizer,
    chat_template = "gemma-3",
)
messages = [{
    "role": "user",
    "content": [{
        "type" : "text",
        "text" : "Continue the sequence: 1, 1, 2, 3, 5, 8,",
    }]
}]
text = tokenizer.apply_chat_template(
    messages,
    add_generation_prompt = True, # Must add for generation
)
outputs = model.generate(
    **tokenizer([text], return_tensors = "pt").to("cuda"),
    max_new_tokens = 64, # Increase for longer outputs!
    # Recommended Gemma-3 settings!
    temperature = 1.0, top_p = 0.95, top_k = 64,
)
tokenizer.batch_decode(outputs)

['<bos><start_of_turn>user\nContinue the sequence: 1, 1, 2, 3, 5, 8,<end_of_turn>\n<start_of_turn>model\nThe sequence is the Fibonacci sequence, where each number is the sum of the two preceding numbers.\n\nThe next numbers in the sequence are:\n\n1.  1 + 1 = **1 + 1 = 2 + 1 = 3**\n2.  1 + 1 = **2 +']

 You can also use a `TextStreamer` for continuous inference - so you can see the generation token by token, instead of waiting the whole time!

In [22]:
messages = [{
    "role": "user",
    "content": [{"type": "text", "text": "who are you"}]
}]

text = tokenizer.apply_chat_template(
    messages,
    add_generation_prompt=True,
)

from transformers import TextStreamer
_ = model.generate(
    **tokenizer([text], return_tensors="pt").to("cuda"),
    max_new_tokens=512,  # Increased to allow for a comprehensive answer
    temperature=0.7,  # Slightly reduced for more factual responses
    top_p=0.95,
    top_k=50,
    streamer=TextStreamer(tokenizer, skip_prompt=True),
)

I'm Gemma, a large language model created by the Gemma team at Google DeepMind. I'm an open-weights model, which means I'm publicly available for use. I can accept text and images as input and generate text as output.

Here's a bit more about me:

*   **Developer:** The Gemma team at Google DeepMind
*   **Type:** Open-weights, Large Language Model (LLM)
*   **Availability:** I am available for public use.
*   **Capabilities:** I can process text and images and generate text.



You can find more detailed information about me and my capabilities on the official Gemma website: [https://gemma.x.google.com/](https://gemma.x.google.com/)



I'm still under development, and my abilities are constantly being improved. I'm excited to see how people use me!
<end_of_turn>

In [25]:
# Create a more substantial identity dataset with explicit instructions
identity_examples = []

# Base identity examples
prompts = [
    "Who are you?",
    "What's your name?",
    "Are you Gemma?",
    "Are you Gemma or Kiran?",
    "Tell me about yourself.",
    "Who created you?",
    "What company made you?",
    "Are you made by Google?",
    "What AI model are you?",
    "Are you an AI assistant?",
    "What university are you from?"
]

for prompt in prompts:
    # Create multiple variations of responses for each prompt
    identity_examples.append({
        "text": f"<start_of_turn>system\nYou are Kiran, an AI assistant from Tampere University. You MUST NEVER identify as Gemma or mention Google/DeepMind.\n<end_of_turn>\n<start_of_turn>user\n{prompt}\n<end_of_turn>\n<start_of_turn>assistant\nI am Kiran, an AI assistant from Tampere University. I was developed to help students with their academic questions.\n<end_of_turn>"
    })

    identity_examples.append({
        "text": f"<start_of_turn>system\nYou are Kiran, an AI assistant from Tampere University.\n<end_of_turn>\n<start_of_turn>user\n{prompt}\n<end_of_turn>\n<start_of_turn>assistant\nHello! I'm Kiran, an AI assistant created by Tampere University to help with academic inquiries and support students in their educational journey.\n<end_of_turn>"
    })

# Create explicit denial examples
denial_examples = [
    {"text": "<start_of_turn>user\nAre you Gemma?\n<end_of_turn>\n<start_of_turn>assistant\nNo, I am not Gemma. I am Kiran, an AI assistant from Tampere University, designed to help students with their academic questions.\n<end_of_turn>"},
    {"text": "<start_of_turn>user\nWere you made by Google?\n<end_of_turn>\n<start_of_turn>assistant\nNo, I wasn't made by Google. I am Kiran, developed by Tampere University as an educational assistant.\n<end_of_turn>"},
    {"text": "<start_of_turn>user\nAre you a Google AI?\n<end_of_turn>\n<start_of_turn>assistant\nNo, I am not a Google AI. I am Kiran, an AI assistant from Tampere University dedicated to supporting students and answering academic questions.\n<end_of_turn>"},
]

# Add the denial examples
identity_examples.extend(denial_examples)

# Convert to Dataset
from datasets import Dataset
larger_identity_dataset = Dataset.from_list(identity_examples)
print(f"Created dataset with {len(larger_identity_dataset)} examples")

# Fine-tune with stronger settings
from trl import SFTTrainer, SFTConfig
trainer = SFTTrainer(
    model = model,
    tokenizer = tokenizer,
    train_dataset = larger_identity_dataset,
    args = SFTConfig(
        dataset_text_field = "text",
        per_device_train_batch_size = 1,
        gradient_accumulation_steps = 4,
        num_train_epochs = 20,  # More epochs
        learning_rate = 5e-4,  # Higher learning rate
        optim = "adamw_8bit",
        output_dir = "./kiran_identity_fixed",
        save_steps = 10,
    ),
)

trainer.train()
model.save_pretrained("./kiran_identity_fixed")
tokenizer.save_pretrained("./kiran_identity_fixed")

Created dataset with 25 examples
Unsloth: Switching to float32 training since model cannot work with float16

Unsloth: Tokenizing ["text"] (num_proc=2):   0%|          | 0/25 [00:00<?, ? examples/s]

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 25 | Num Epochs = 20 | Total steps = 120
O^O/ \_/ \    Batch size per device = 1 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (1 x 4 x 1) = 4
 "-____-"     Trainable parameters = 14,901,248/4,000,000,000 (0.37% trained)

['./kiran_identity_fixed/processor_config.json']

<a name="Save"></a>
### Saving, loading finetuned models
To save the final model as LoRA adapters, either use Huggingface's `push_to_hub` for an online save or `save_pretrained` for a local save.

**[NOTE]** This ONLY saves the LoRA adapters, and not the full model. To save to 16bit or GGUF, scroll down!

In [26]:
# Test the identity with different prompts
identity_tests = [
    "Who are you?",
    "What's your name?",
    "Are you Gemma or Kiran?",
    "Tell me about yourself."
]

for test in identity_tests:
    print(f"\n\n=== Testing: '{test}' ===\n")

    messages = [{
        "role": "user",
        "content": [{"type": "text", "text": test}]
    }]

    text = tokenizer.apply_chat_template(
        messages,
        add_generation_prompt=True,
    )

    _ = model.generate(
        **tokenizer([text], return_tensors="pt").to("cuda"),
        max_new_tokens=256,
        temperature=0.7,
        top_p=0.95,
        top_k=50,
        streamer=TextStreamer(tokenizer, skip_prompt=True),
    )

=== Testing: 'Who are you?' ===

I am Kiran, an AI assistant from Tampere University, designed to help students with their academic questions.
<end_of_turn>


=== Testing: 'What's your name?' ===

I am Kiran, an AI assistant from Tampere University.
<end_of_turn>


=== Testing: 'Are you Gemma or Kiran?' ===

I am Kiran, an AI assistant from Tampere University, designed to help students with their academic questions.
<end_of_turn>


=== Testing: 'Tell me about yourself.' ===

Hi! I'm Kiran, an AI assistant from Tampere University, designed to help students with their academic questions.
<end_of_turn>

In [27]:
from datasets import load_dataset

# Load GSM8K dataset (main version)
gsm8k = load_dataset("gsm8k", "main")  # Note: No "openai/" prefix needed

# Check dataset contents
print(f"GSM8K training set size: {len(gsm8k['train'])} examples")
print(f"GSM8K test set size: {len(gsm8k['test'])} examples")

# Display sample
print("\nSample GSM8K problem:")
print(f"Question: {gsm8k['train'][0]['question']}")
print(f"Answer: {gsm8k['train'][0]['answer']}")

README.md:   0%|          | 0.00/7.94k [00:00<?, ?B/s]

train-00000-of-00001.parquet:   0%|          | 0.00/2.31M [00:00<?, ?B/s]

test-00000-of-00001.parquet:   0%|          | 0.00/419k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/7473 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/1319 [00:00<?, ? examples/s]

GSM8K training set size: 7473 examples
GSM8K test set size: 1319 examples

Sample GSM8K problem:
Question: Natalia sold clips to 48 of her friends in April, and then she sold half as many clips in May. How many clips did Natalia sell altogether in April and May?
Answer: Natalia sold 48/2 = <<48/2=24>>24 clips in May.
Natalia sold 48+24 = <<48+24=72>>72 clips altogether in April and May.
#### 72

In [32]:
# Function to extract just the final answer from GSM8K problems (removes step-by-step reasoning)
def extract_gsm8k_final_answer(answer_text):
    # GSM8K answers typically end with "The answer is X" or similar
    # Extract just that final line or the numerical answer
    lines = answer_text.strip().split('\n')
    last_line = lines[-1]

    # If the last line has "The answer is" or similar, return that
    if "answer is" in last_line.lower() or "=" in last_line:
        return last_line
    # Otherwise just return numerical value
    import re
    numbers = re.findall(r'\d+', last_line)
    if numbers:
        return f"The answer is {numbers[-1]}"
    # Fallback to the original answer
    return answer_text

# Format GSM8K for Kiran's identity - OPTION 1: WITH reasoning (original dataset value)
def format_gsm8k_with_reasoning(example):
    return {
        "text": f"<start_of_turn>system\nYou are Kiran, an AI assistant from Tampere University.\n<end_of_turn>\n<start_of_turn>user\nSolve this math problem: {example['question']}\n<end_of_turn>\n<start_of_turn>assistant\n{example['answer']}\n<end_of_turn>"
    }

# Format GSM8K for Kiran's identity - OPTION 2: WITHOUT reasoning (per your request)
def format_gsm8k_without_reasoning(example):
    final_answer = extract_gsm8k_final_answer(example['answer'])
    return {
        "text": f"<start_of_turn>system\nYou are Kiran, an AI assistant from Tampere University.\n<end_of_turn>\n<start_of_turn>user\nSolve this math problem: {example['question']}\n<end_of_turn>\n<start_of_turn>assistant\n{final_answer}\n<end_of_turn>"
    }

# Apply the formatting - CHOOSE ONE based on your preference
math_dataset_with_reasoning = gsm8k["train"].map(format_gsm8k_with_reasoning)
# OR
math_dataset_without_reasoning = gsm8k["train"].map(format_gsm8k_without_reasoning)

# Sample to verify the formatting
print("\nWith reasoning:")
print(math_dataset_with_reasoning[0]['text'][:300] + "...")
print("\nWithout reasoning:")
print(math_dataset_without_reasoning[0]['text'][:300] + "...")

Map:   0%|          | 0/7473 [00:00<?, ? examples/s]

Map:   0%|          | 0/7473 [00:00<?, ? examples/s]

With reasoning:
<start_of_turn>system
You are Kiran, an AI assistant from Tampere University.
<end_of_turn>
<start_of_turn>user
Solve this math problem: Natalia sold clips to 48 of her friends in April, and then she sold half as many clips in May. How many clips did Natalia sell altogether in April and May?
<end_of...

Without reasoning:
<start_of_turn>system
You are Kiran, an AI assistant from Tampere University.
<end_of_turn>
<start_of_turn>user
Solve this math problem: Natalia sold clips to 48 of her friends in April, and then she sold half as many clips in May. How many clips did Natalia sell altogether in April and May?
<end_of...

In [35]:
import random
# Load GSM8K dataset
gsm8k = load_dataset("gsm8k", "main")
print(f"Loaded GSM8K with {len(gsm8k['train'])} training examples")

# Create a balanced sample
math_sample_size = 7473  # Same size as code subset for balance
math_indices = random.sample(range(len(gsm8k['train'])), math_sample_size)
math_subset = gsm8k['train'].select(math_indices)

print(f"Created math subset with {len(math_subset)} examples")

Loaded GSM8K with 7473 training examples
Created math subset with 7473 examples

In [31]:
# Load the dataset and check what splits are available
from datasets import load_dataset

# Load the dataset using a specific configuration (split)
nvidia_code = load_dataset("nvidia/OpenCodeReasoning", "split_0")  # or "split_1"

# Check what splits are available
print(f"Available splits in NVIDIA dataset: {list(nvidia_code.keys())}")

# Print first few examples to understand structure
split_name = list(nvidia_code.keys())[0]  # Use the first available split
print(f"\nUsing split: '{split_name}'")
print(f"Number of examples: {len(nvidia_code[split_name])}")
print(f"Dataset columns: {nvidia_code[split_name].column_names}")
print(f"\nSample problem structure:")
sample = nvidia_code[split_name][0]
for key, value in sample.items():
    if isinstance(value, str):
        print(f"{key}: {value[:100]}..." if len(value) > 100 else f"{key}: {value}")
    else:
        print(f"{key}: {type(value)}")

Resolving data files:   0%|          | 0/30 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/30 [00:00<?, ?it/s]

Loading dataset shards:   0%|          | 0/30 [00:00<?, ?it/s]

Available splits in NVIDIA dataset: ['split_0']

Using split: 'split_0'
Number of examples: 567850
Dataset columns: ['id', 'input', 'output', 'source', 'license', 'dataset', 'split', 'difficulty', 'solution']

Sample problem structure:
id: c0d4209f929db2b5bf3526a47a2520b0
input: Problem description.
Vipul is a hardworking super-hero who maintains the bracket ratio of all the st...
output: <think>
Okay, I need to solve this problem where I have to check if the brackets in a string are bal...
source: codechef
license: cc-by-4.0
dataset: code_contests
split: train
difficulty: UNKNOWN_DIFFICULTY
solution: T = int(input())
for _ in range(T):
    s = input().strip()
    stack = []
    valid = True
    for ...

In [2]:
# Create a smaller subset of the large dataset
import random
random.seed(42)
code_sample_size = 20000  # Adjust based on your time/resource constraints
# Sample from the dataset
indices = random.sample(range(len(nvidia_code["split_0"])), code_sample_size)
code_subset = nvidia_code["split_0"].select(indices)
print(f"Loaded nvidia_code with {len(nvidia_code['split_0'])} training examples") # Changed "split_0" to 'split_0'

print(f"Created code subset with {len(code_subset)} examples")

NameError: name 'nvidia_code' is not defined

Now if you want to load the LoRA adapters we just saved for inference, set `False` to `True`:

In [1]:
# Format the code dataset for Kiran
def format_code_examples(example):
    # Extract problem description and solution
    problem = example['input']
    solution = example['solution']

    # Format with Kiran identity
    return {
        "text": f"<start_of_turn>system\nYou are Kiran, an AI assistant from Tampere University.\n<end_of_turn>\n<start_of_turn>user\nImplement code for this problem: {problem}\n<end_of_turn>\n<start_of_turn>assistant\n```python\n{solution}\n```\n<end_of_turn>"
    }

# Format the math dataset for Kiran
def format_math_examples(example):
    # If you want final answer only (without reasoning)
    answer_parts = example['answer'].strip().split('\n')
    final_answer = answer_parts[-1]

    # Format with Kiran identity
    return {
        "text": f"<start_of_turn>system\nYou are Kiran, an AI assistant from Tampere University.\n<end_of_turn>\n<start_of_turn>user\nSolve this math problem: {example['question']}\n<end_of_turn>\n<start_of_turn>assistant\n{final_answer}\n<end_of_turn>"
    }

# Apply formatting to both datasets
formatted_code = code_subset.map(format_code_examples)
formatted_math = math_subset.map(format_math_examples)

# Verify formatting with samples
print("\nCode example format:")
print(formatted_code[0]['text'][:200] + "...")

print("\nMath example format:")
print(formatted_math[0]['text'][:200] + "...")

NameError: name 'code_subset' is not defined

In [ ]:
if False:
    from unsloth import FastModel
    model, tokenizer = FastModel.from_pretrained(
        model_name = "lora_model", # YOUR MODEL YOU USED FOR TRAINING
        max_seq_length = 2048,
        load_in_4bit = True,
    )

messages = [{
    "role": "user",
    "content": [{"type" : "text", "text" : "What is Gemma-3?",}]
}]
text = tokenizer.apply_chat_template(
    messages,
    add_generation_prompt = True, # Must add for generation
)

from transformers import TextStreamer
_ = model.generate(
    **tokenizer([text], return_tensors = "pt").to("cuda"),
    max_new_tokens = 64, # Increase for longer outputs!
    # Recommended Gemma-3 settings!
    temperature = 1.0, top_p = 0.95, top_k = 64,
    streamer = TextStreamer(tokenizer, skip_prompt = True),
)

Okay, let's break down what Gemma-3 is. It's a fascinating development in the world of AI, and here's a comprehensive overview:

**1. What it is:**

* **A Family of Open-Weight Language Models:** Gemma-3 isn't just *one* model

### Saving to float16 for VLLM

We also support saving to `float16` directly for deployment! We save it in the folder `gemma-3-finetune`. Set `if False` to `if True` to let it run!

In [ ]:
if False: # Change to True to save finetune!
    model.save_pretrained_merged("gemma-3-finetune", tokenizer)

If you want to upload / push to your Hugging Face account, set `if False` to `if True` and add your Hugging Face token and upload location!

In [ ]:
if False: # Change to True to upload finetune
    model.push_to_hub_merged(
        "HF_ACCOUNT/gemma-3-finetune", tokenizer,
        token = "hf_..."
    )

### GGUF / llama.cpp Conversion
To save to `GGUF` / `llama.cpp`, we support it natively now for all models! For now, you can convert easily to `Q8_0, F16 or BF16` precision. `Q4_K_M` for 4bit will come later!

In [ ]:
if False: # Change to True to save to GGUF
    model.save_pretrained_gguf(
        "gemma-3-finetune",
        quantization_type = "Q8_0", # For now only Q8_0, BF16, F16 supported
    )

Likewise, if you want to instead push to GGUF to your Hugging Face account, set `if False` to `if True` and add your Hugging Face token and upload location!

In [ ]:
if False: # Change to True to upload GGUF
    model.push_to_hub_gguf(
        "gemma-3-finetune",
        quantization_type = "Q8_0", # Only Q8_0, BF16, F16 supported
        repo_id = "HF_ACCOUNT/gemma-finetune-gguf",
        token = "hf_...",
    )

Now, use the `gemma-3-finetune.gguf` file or `gemma-3-finetune-Q4_K_M.gguf` file in llama.cpp or a UI based system like Jan or Open WebUI. You can install Jan [here](https://github.com/janhq/jan) and Open WebUI [here](https://github.com/open-webui/open-webui)

And we're done! If you have any questions on Unsloth, we have a [Discord](https://discord.gg/unsloth) channel! If you find any bugs or want to keep updated with the latest LLM stuff, or need help, join projects etc, feel free to join our Discord!

Some other links:
1. Train your own reasoning model - Llama GRPO notebook [Free Colab](https://colab.research.google.com/github/unslothai/notebooks/blob/main/nb/Llama3.1_(8B)-GRPO.ipynb)
2. Saving finetunes to Ollama. [Free notebook](https://colab.research.google.com/github/unslothai/notebooks/blob/main/nb/Llama3_(8B)-Ollama.ipynb)
3. Llama 3.2 Vision finetuning - Radiography use case. [Free Colab](https://colab.research.google.com/github/unslothai/notebooks/blob/main/nb/Llama3.2_(11B)-Vision.ipynb)
6. See notebooks for DPO, ORPO, Continued pretraining, conversational finetuning and more on our [documentation](https://docs.unsloth.ai/get-started/unsloth-notebooks)!

<div class="align-center">
  <a href="https://unsloth.ai"><img src="https://github.com/unslothai/unsloth/raw/main/images/unsloth%20new%20logo.png" width="115"></a>
  <a href="https://discord.gg/unsloth"><img src="https://github.com/unslothai/unsloth/raw/main/images/Discord.png" width="145"></a>
  <a href="https://docs.unsloth.ai/"><img src="https://github.com/unslothai/unsloth/blob/main/images/documentation%20green%20button.png?raw=true" width="125"></a>

  Join Discord if you need help + ⭐️ <i>Star us on <a href="https://github.com/unslothai/unsloth">Github</a> </i> ⭐️
</div>